nicklockwood/SwiftFormat

README.md

Suggest git hook

---

README.md
SwiftFormat.podspec.json

This PR updates instructions related to https://github.com/nicklockwood/SwiftFormat/pull/92#issuecomment-282127636.

Add an instruction to install the CLI tool via CocoaPods.

---

Sources/CommandLine.swift

This adds a new commandline option `--dry` that when specified
prevents actual file changes and instead prints out a log message
for every file that would have been changed.
Relates to #155

Add dry mode

---

CommandLineTool/main.swift
Sources/CommandLine.swift
Tests/CommandLineTests.swift

Add lint option

---

Sources/Tokenizer.swift
Tests/TokenizerTests.swift

Fixed custom operator tokenisation

---

CommandLineTool/main.swift

Spotted another one of these :)

Fixed stdout vs stderr tty detection

---

README.md

As titled, minor fix on README

Fix up markdown syntax

---

EditorExtension/Extension/FormatEntireFileCommand.swift
EditorExtension/Extension/FormatSelectedSourceCommand.swift
EditorExtension/Extension/SupportedContentUTIs.swift
SwiftFormat.xcodeproj/project.pbxproj

Xcode Extension - Adds support for swift package manifest files

---

README.md

Make indent option value consistent with the CLI help

---

README.md

Also removed trailing or superfluous whitespaces.

Added missing punctuation in README

---

EditorExtension/Application/Base.lproj/Main.storyboard
EditorExtension/Application/Source/RulesViewController.swift

- Add a search bar to filter rules
- Remove a crashing forced unwrap

Add a search bar to filter rules

---

Rules.md
Sources/OptionDescriptor.swift
Sources/Options.swift
Sources/Rules.swift
Tests/RulesTests+Organization.swift
Tests/XCTestManifests.swift

Add support for sorting imports based on length

Sort imports by length

---

README.md

Added section to README.md for Bazel build usage.

---

Sources/Arguments.swift
Sources/CommandLine.swift
Tests/CommandLineTests.swift

Fixes https://github.com/nicklockwood/SwiftFormat/issues/1228
@nicklockwood I haven't been able to compile and run tests neither opening the Package.swift, nor opening the xcodeproj, as both are giving me compilation errors. Could you please provide some guidance on it? 🙏

Support for script input

---

Sources/Tokenizer.swift
Tests/TokenizerTests.swift

Fixes #1243 
Fixes the bug and adds a test case.

Fixes issue where "case" was treated as endOfScope when preceeded by "await"

---

Rules.md
Sources/Examples.swift
Sources/FormattingHelpers.swift
Sources/OptionDescriptor.swift
Sources/Options.swift
Sources/Rules.swift
Tests/MetadataTests.swift
Tests/RulesTests+Wrapping.swift

Refresh https://github.com/nicklockwood/SwiftFormat/pull/859
Rebase on `develop` and fix conflicts. 
As that MR had already pass your review originally, I hope it won't be tough and soon will be part of the release.

Wrap options

---

Rules.md
Sources/Rules.swift
Tests/RulesTests+Syntax.swift

I am adding `hoistAwait` rule based on [this](https://github.com/nicklockwood/SwiftFormat/issues/948) issue.
I've followed `hoistLet` rule. I'll try to work on a better abstraction since `hoistTry` can also be implemented similarly.

feat: `hoistAwait` rule

---

Sources/Arguments.swift
Sources/CommandLine.swift
Sources/GithubActionsLogReporter.swift
Sources/JSONReporter.swift
Sources/Reporter.swift
SwiftFormat.xcodeproj/project.pbxproj
Tests/CommandLineTests.swift
Tests/GithubActionsLogReporterTests.swift
Tests/GlobsTests.swift
Tests/SwiftFormatTests.swift

Implements https://github.com/nicklockwood/SwiftFormat/issues/1365

enhancement: Github Actions annotations reporter

---

Rules.md
Sources/Rules.swift
Tests/RulesTests+Syntax.swift

Adding `hoistTry` rule based on [this](https://github.com/nicklockwood/SwiftFormat/issues/948) issue. 
The PR consists of commits:
1. Basic rule implementation
2. Added postfix related code to avoid hoisting those.
3. Added a few more tests.

feat: `hoistTry` rule

---

Sources/FormattingHelpers.swift
Tests/RulesTests+Syntax.swift

A quick fix for https://github.com/nicklockwood/SwiftFormat/issues/1388

fix: hoistTry string interpolation

---

Sources/Rules.swift
Tests/RulesTests+Organization.swift

A fix for https://github.com/nicklockwood/SwiftFormat/issues/1453

fix: sortedSwitchCases breaking return value

---

README.md

Fix incorrect shell comman in README

---

Plugins/SwiftFormatPlugin/SwiftFotmatPluginXcode.swift

Fix xcode command plugin

---

EditorExtension/Application/Source/AboutViewController.swift

Update to match System Settings name change from macOS Ventura 13.0.

Change System Preferences to System Settings

---

README.md

Just adds two things that weren't immediately obvious to me.

Add GitHub actions and swiftversion info to README

---

Sources/Reporter.swift
Sources/XMLReporter.swift
SwiftFormat.xcodeproj/project.pbxproj
Tests/CommandLineTests.swift

Related to #1673 
XML reporter has been Implemented and added to the reporter option.

Add XML reporter

---

README.md

Looks like the readme got out of sync when the placeholders were updated, this PR updates it to match the code currently in main 🙂

Update file header placeholders documentation to match the code

---

Package@swift-5.6.swift

Fix Xcode 16 Beta 4 warnings related to unhandled files

---

.github/workflows/build.yml

 GitHub Actions build on macOS v14 on ARM 64 on develop branch

---

Dockerfile

fixes #1930 
Someone please test if the issue is fixed with this image: ghcr.io/cyberbeni/swiftformat:github_actions_fix

Fix docker container compatibility with GitHub Actions

---

README.md

https://github.com/actions/checkout/releases

Upgrade GitHub Action checkout

---

Rules.md
Sources/Rules/OrganizeDeclarations.swift

This pull request adds documentation for SwiftFormat, specifically addressing the behavior of property reordering in `struct` types.

Update `organizeDeclarations` documentation

---

.github/workflows/build.yml
.github/workflows/windows_release.yml

This PR tries to fix the Windows build, which is currently failing.

Try to fix Windows build

---

Sources/ParsingHelpers.swift
Tests/ParsingHelpersTests.swift

This PR adds a `parseFunctionDeclaration` helper that parses a full function declaration, handling all of the elements that can be optional like generic parameters, async/throws effects, a return type, a where clause, and an optional body.
This will make it easier to write rules that inspect function signatures.
For example we noticed that `--wrapeffects` doesn't currently work on protocol definitions because it expects there to be a `.startOfScope("{")` that it can use to find the effects. Consolidating this parsing in a single helper will help avoid these sorts of edge cases.

Add helper to parse full function declarations

---

Sources/Rules/TrailingCommas.swift
Tests/Rules/TrailingCommasTests.swift

This PR updates the `trailingCommas` rule to handle edge cases where Swift 6.1 unexpectedly doesn't allow trailing commas:
- https://github.com/swiftlang/swift/issues/81474
- https://github.com/swiftlang/swift/issues/81475
Fixes https://github.com/nicklockwood/SwiftFormat/issues/2039.

Update `trailingCommas` rule to handle edge cases where Swift 6.1 unexpectedly doesn't allow trailing commas

---

.github/workflows/docker.yml

This PR updates the docker upload job to run automatically for new releases.

Update docker job to run automatically for new releases

---

Sources/Rules/TrailingCommas.swift
Tests/Rules/TrailingCommasTests.swift

Fix issue where trailing commas were unexpectedly removed from initializer argument lists

---

Sources/CommandLine.swift
Tests/CommandLineTests.swift

This PR improves markdown code block parsing to better handle nested code blocks.

Improve parsing of nested markdown code blocks
