nicklockwood/SwiftFormat

CommandLineTool/main.swift, LICENCE.md, README.md, SwiftFormat.xcodeproj/project.pbxproj, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat (Xcode Source Editor Extension).xcscheme, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat for Xcode.xcscheme, SwiftFormat/Formatter.swift, SwiftFormat/Info.plist, SwiftFormat/Rules.swift, SwiftFormat/SwiftFormat.h, SwiftFormat/SwiftFormat.swift, SwiftFormat/Tokenizer.swift, SwiftFormatTests/Info.plist, SwiftFormatTests/RulesTests.swift, SwiftFormatTests/SwiftFormatTests.swift, SwiftFormatTests/TokenizerTests.swift, Xcode Source Editor Extension/Application/AppDelegate.swift, Xcode Source Editor Extension/Application/Assets.xcassets/AppIcon.appiconset/Contents.json, Xcode Source Editor Extension/Application/Base.lproj/Main.storyboard, Xcode Source Editor Extension/Application/Info.plist, Xcode Source Editor Extension/Application/SwiftFormatter.entitlements, Xcode Source Editor Extension/Application/ViewController.swift, Xcode Source Editor Extension/Extension/CommandErrors.swift, Xcode Source Editor Extension/Extension/FormatEntireFileCommand.swift, Xcode Source Editor Extension/Extension/FormatSelectedSourceCommand.swift, Xcode Source Editor Extension/Extension/Info.plist, Xcode Source Editor Extension/Extension/SourceEditorCommand.swift, Xcode Source Editor Extension/Extension/SourceEditorExtension.swift, Xcode Source Editor Extension/Extension/SwiftFormatter.entitlements
This PR introduces an Xcode Source Editor Extension for SwiftFormat.
It works, but there are a few things still left to sort out, namely:
To use this PR, you will need to archive and export the application target using a proper certificate. Unsigned or improperly signed application/application extensions are not loaded by Xcode 8.x.
Here's a preview release: [SwiftFormat for Xcode 0.12.zip](https://github.com/nicklockwood/SwiftFormat/files/521015/SwiftFormat.for.Xcode.0.12.zip)
You'll need to enable the extension in System Preferences → Extensions:
After relaunching Xcode, you should be able to set a keyboard shortcut for this as follows:
No promises, ensure you're not working with uncommitted code, etc, etc.
=> Xcode source editor extension

SwiftFormat.podspec.json
Enables to install the CLI tool with CocoaPods.
Related: https://github.com/nicklockwood/SwiftFormat/issues/91
=> Include swiftformat binary.

README.md
I saw that `numberFormatting` was not in the README. I updated it following the [0.24 CHANGELOG](https://github.com/nicklockwood/SwiftFormat/blob/cb5dcfe8d3bb80b3a50722e15678209f078a9d6e/CHANGELOG.md#024-2017-01-18)
=> Update README for numberFormatting

README.md
I really like this project! I had a bit of trouble navigation the README and viewing what rules did what, so I made some alterations that will hopefully help others in the future and make updating any rules in the README easier on the maintainers in the future.
This commit changes the space-based view of the rules code to a Github-supported markdown extension that shows diffs. This commit also adds a table of contents to help navigate the long readme and polishes the wording of some of the rule explanations.
=> Add to README: diff view to rules, table of contents, wording polish

Sources/Rules.swift, Tests/RulesTests.swift
As reported in issue #136, current redundantParens rule also remove the parens from method in for loop, where condition. This PR try to resolve the same via added `where` token check.
=> This resolves parentheses removal issue in case`for condition where method() {}`

README.md, Sources/Rules.swift, Tests/RulesTests.swift
Hi there!
I've tried to implement the removal of redundant .init calls when creating instances because is something that I keep seeing in PRs.
Feel free to provide any feedback to improve the implementation, specially around knowing if an identifier is a type. 
I wrote as much tests as I could come up with, also taken from SwiftLint https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/ExplicitInitRule.swift#L18 as mentioned in #130. Not sure if there is something that already does that in the codebase.
=> Remove explicit .init

README.md
Today I had some issues with whitespaces using ``git status --porcelain``. 
Before adding a file, the result from above was like
``
[:space:]M[:space:]path/to/file.swift
``
and after adding it was like
``
M[:space:]path/to/file.swift
``
Therefore I changed the line, detecting the changes to the following:
``
git diff --staged --name-only | grep -e '\(.*\).swift$'
``
=> Update README.md - Fix git pre-commit hook whitespace issue

README.md, Sources/Rules.swift, Tests/CommandLineTests.swift, Tests/FormatterTests.swift, Tests/OptionsTests.swift, Tests/PerformanceTests.swift, Tests/RulesTests.swift, Tests/SwiftFormatTests.swift, Tests/TokenizerTests.swift
This adds a rule to sort imports alphabetically for consistency.
I didn't disable it by default, but if you think it should be I can do that.
=> Add sortedImports rule

Sources/CommandLine.swift, Sources/SwiftFormat.swift
A single variable was being captured by a block and modified while also being passed by inout reference
See: https://github.com/apple/swift-evolution/blob/master/proposals/0176-enforce-exclusive-access-to-memory.md
=> Fix "exclusive accesses" violations

README.md
This PR adds instructions to setup SwiftFormat with [Danger](http://danger.systems/ruby/) using the [danger-swiftformat](https://github.com/garriguv/danger-ruby-swiftformat) plugin.
cf https://github.com/nicklockwood/SwiftFormat/issues/66
=> Add instructions for danger-swiftformat

EditorExtension/Application/SwiftFormatter.entitlements, EditorExtension/Extension/SwiftFormatter.entitlements
This is a follow up on #212 refactoring. 
The key for UserDefaults group domain was change to "com.charcoaldesign.SwiftFormat" to be the same as the bundle ID of the Framework target. But it was not change in the capabilities tab of the App and the Extension. 
Consequence: the app and the Xcode extension currently don't share their rules settings, meaning that the extension will always use the default rules and never the user defined one.
=> Allow Communication between the Xcode Extension and Companion App

.gitignore, CommandLineTool/main.swift, Package.swift, Sources/CommandLine.swift
Resolves #178 
To get Swiftformat working with Swift PM a couple of things had to be done:
- define products and targets
- make Swiftformat a dependency of CommandLineTool
- make certain things public in SwiftFormat for CommandLineTool
- change a OSX 10.11+ api call (SPM defaults to OSX 10.10)
- update the Swiftformat.xcodeproj to remove the Swiftformat sources from CommandLineTool and make SwiftFormat a dependency of CommandLintTool
This leave the current directory structure and target names intact.
=> Build with Swift PM

Package.swift
I tried to use SwiftFormat as dependency within my Swift Package Manager project.
Although the core library has not been exported. This PR does add the export. 
I called the library `SwiftFormatCore` to match the subspec's name within `SwiftFormat.podspec.json`.
=> Export SwiftFormat for SPM

.pre-commit-hooks.yaml
#183 makes possible to use [pre-commit](https://github.com/pre-commit/pre-commit) tool to manage and sync git hooks. I add required for that .pre-commit-hook.yaml file. 
Unfortunately, that tool can't update files and can only use for the check but I think it can be useful for some dev workflows.
=> Add integration with pre-commit tool

Sources/CommandLine.swift, Tests/CommandLineTests.swift
Fixes the case when passing absolute paths as inputs would raise an error.
Example:
```lang=sh
$ swiftformat /Users/thelvis4/test.swift
running swiftformat...
error: file not found at /Users/thelvis4//Users/thelvis4/test.swift
```
=> Handle absolute paths

README.md
- Update the git pre-commit hook instruction to exclude all the deleted files from going through SwiftFormat.
=> Excluding deleted swift files from pre-commit hook

Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests.swift
Added `preserving` arguments wrap rule: if it finds that there's a newline before the first argument, it uses `beforeFirst` rule, and `afterFirst` otherwise.
=> Added preserving wrap mode

Sources/Formatter.swift, Tests/FormatterTests.swift
We use SwiftFormat in our project together with Sourcery as a build step, and we face an issue where Sourcery and SwiftFormatter are overriding each other in some cases. I know, there is a possibility to use `--exclude` but this requires to pass paths, and we use our Sourcery templates in many projects in one big workspace, so it is not exactly easy to get all paths. It would be easier for us to specify one line in our templates.
SwiftLint offers this option, so it is not entirely out of mind.
Even if you don't like my implementation that is rather basic and expands the current simple implementation please still consider adding this.
Thank you.
=> Add support for swiftformat:enable:all and swiftformat:disable:all

EditorExtension/Application/Source/AppDelegate.swift, Sources/Arguments.swift, Tests/ArgumentsTests.swift
This PR is a follow-up to the issue ***.swiftformat file should end with a linefeed in all configurations #293***.
After a further study of the SwiftFormat code and the use of `func serialize(options:excludingDefaults:separator:) -> String`, I deviated from my first patch.
This PR 
- modifies `func serialize` to make sure that it returns a string without a trailing separator
- adds 4 tests to verify above behavior, for principal use cases 
- modifies `func saveConfiguration` to add a newline to a nonempty config string
The modified code passes manual tests with saving the settings of `SwiftFormat for Xcode` to a `.swiftformat` file:
- `Reset to Defaults` + `Save`: `.swiftformat` is empty (0 length)
- `Reset to Defaults` + uncheck `Infer Automatically from Source Files`,
- `Reset to …
=> Rf develop newline at swiftformat eof

README.md
This PR forwards changes from vknabel/vscode-swiftformat#1
> **Remove unrequired mint param**
> This is no longer needed in Mint, as it reads the executable name from the package 😀
> It wasn’t required for macOS anyway as it used to take the repo name by default
> *by [@yonaskolb](https://github.com/yonaskolb)*
=> Omit unrequired parameter for Mint install

README.md
Thanks so much for creating SwiftFormat!
I found the onboarding process a bit confusing.  The README describes all of the rules, but then you have to run `swiftformat --help` to find the options for those rules.
This PR adds the config options to the rule descriptions in the README, so that new users don't have to piece together the documentation from several places while getting started.
=> Adding config options to rule descriptions.

README.md
Just noticed a minor typo when setting up my own config, thanks 😄
=> Remove extra space in `--exclude` config example

Sources/Rules.swift, Tests/RulesTests.swift
Whilst Apple does recommend strong IBOutlets, this rule can't apply to delegates. This proposal disables the rules if any of the identifiers in the scope contain the string `delegate`.
I realise that this does rely on Cocoa conventions, that delegates as IBOutlets might be an uncommon pattern, and it can be worked around using `// swiftformat:disable:next strongOutlets`, but I think this change is still worthwhile to avoid potential unexpected retain cycles after applying SwiftFormat.
Looking forward to hearing your thoughts on this 😄
=> Don't apply strongOutlets to delegates

Sources/Formatter.swift, Sources/Rules.swift, Tests/RulesTests.swift
I've been integrating SwiftFormat into my existing codebase (which already uses SwiftLint) and I've found that the `--wrapcollections beforefirst` rule doesn't behave exactly how I'd expect it to. I've never written or worked on a parser but have tried to isolate my changes to this very specific case.
At a high level: SwiftFormat currently only considers whether the current scope contains new lines when applying any of the `wrapcollections` rules and ignores any new lines in nested scopes (by design). This proposal modifies the `beforeFirst` rule specifically so that it is applied to a collection if any of the sub-scopes contain new lines. The examples below outline the scope of what I intend my changes to achieve.
I'd appreciate any feedback on a) the basic premise of the proposal, b) …
=> Extend `--wrapCollections beforeFirst` to nested collections

README.md, Sources/CommandLine.swift, Sources/Options.swift, Sources/OptionsDescriptor.swift, Sources/Rules.swift, Tests/ArgumentsTests.swift, Tests/RulesTests.swift
This PR adds a config option to group `@testable import`s at the top or bottom when sorting them.
This way instead of:
```swift
import Bar
@testable import Foo
import UIKit
```
we could get:
```swift
import Bar
import UIKit
@testable import Foo
```
or:
```swift
@testable import Foo
import Bar
import UIKit
```
This is a style I've seen in some projects, putting the `@testable` at the bottom so it's easier to know what module is being tested.
_This is my first PR to `SwiftFormat` so I'm more than happy to revisit anything._
=> Add option to group @testable imports at the top or bottom

EditorExtension/Application/Source/AppDelegate.swift
Hi @nicklockwood ,
I've encounter a problem with saved options due to the fact that I've originally develop the format saved into UserDefault to use Options ID instead of argumentName as key.
Because of that my store was not clean and options were always change for the default and the keys were never properly updated.
It got me thinking that if a change of key would occur in the future there would be no way for the end user to reset his store to a clean state, as a way to restore proper behaviour.
I'm not sure this pull request represent the best way to deal with it.
I would appreciate your opinion on the subject.
=> Remove all in UserDefaults associated with the group on reset to default

Package.swift
I have a PR adding support for SwiftFormat being installed locally to vscode ( https://github.com/vknabel/vscode-swiftformat/pull/2 ) and realized that this is the only instance when the capitalization is different and so I _assume_ that this is a bug?
This fixes the command to be consistent with all the rest of the docs 👍
=> Renames the app to "swiftformat" when coming in via SPM

Package.swift, Tests/PerformanceTests.swift
Danger Swift won't run tests on Linux because this lib and CryptoSwift both happen to use the word "Tests" for your tests, turns out that's in a global namespace in SwiftPM. Who knew? 
See: https://travis-ci.org/danger/swift/jobs/468922700#L524 ( from https://github.com/danger/swift/pull/145 )
So, this PR fixes that, and then also makes tests run via `swift test`, before:
After:
> Executed 1362 tests, with 1 failure (0 unexpected) in 460.674 (460.940) seconds
and if you're interested
> /Users/ortatherox/dev/projects/oss/swift/libs/SwiftFormat/Tests/SwiftFormatTests.swift:263: error: -[SwiftFormatTests.SwiftFormatTests testDoubleWildcardMatchesDirectorySlash] : XCTAssertEqual failed: ("2") is not equal to ("1") -
Looks unrelated to my change though, so I'm not gonna go after it.
=> Rename the test target to not clash with other 'test' targets

Rules.md
There are several mistakes inside `Rules.md` file connected with examples of next rules:
- `redundantExtensionACL` rule has example of `redundantGet` one
-  `redundantLet` rule has example of `redundantExtensionACL` one
-  the example of `strongOutlets` was inside `strongifiedSelf` one
=> Fix mistakes in `Rules.md` file.

EditorExtension/Application/Info.plist, EditorExtension/Application/Source/AppDelegate.swift, EditorExtension/Application/Source/OptionsViewController.swift, EditorExtension/Application/Source/RulesViewController.swift
Hi @nicklockwood ,
This pull request is to be able to:
1. Drag and drop a . swiftformat file on the app icon to have it load the configuration into the application
2. Double click on a . swiftformat file an have it open the application and load the configuration
3. Be able to use the "open" command in the terminal with a config file as parameter and have it being loaded in the application
4. Fix the Open Recent not updating the UI
5. Fix not compiling develop branch
We were mostly interested in point 3, because we are scripting our "new guy" computer setup and we wanted to be able to add Swift Format to the computer and have it load our default config file for the Xcode extension.
=> Associate . swiftformat file format with the SwiftFormat for Xcode

EditorExtension/Application/Base.lproj/Main.storyboard, EditorExtension/Application/Source/RulesViewController.swift
| Before this PR  | After this PR |
| ------------- | ------------- |
| <img width="612" alt="image" src="https://user-images.githubusercontent.com/4802/54466600-7d292c80-47d4-11e9-8316-f18b73fa8f87.png"> | <img width="612" alt="image" src="https://user-images.githubusercontent.com/4802/54466510-2ae80b80-47d4-11e9-8c39-c833ea5264f6.png"> |
| <img width="612" alt="image" src="https://user-images.githubusercontent.com/4802/54466578-70a4d400-47d4-11e9-85a1-9ad9192e2bf5.png"> | <img width="612" alt="image" src="https://user-images.githubusercontent.com/4802/54466590-769ab500-47d4-11e9-9483-ba27682d68ca.png"> |
Not sure about the colouring of the light mode rows, but they're both readable now.
=> Fix dark mode

Sources/Rules.swift, Tests/RulesTests.swift
This pull request adds a test for #417 
~I probably won't be able to fix this myself, but thought at least a test for reproducing it might be useful.~ I came up with a very simplistic fix. I don't claim to have a deep understanding of the codebase though so this might not be enough.
=> don't add self in front of parameter names

Tests/RulesTests.swift
Similar to #418, `if case let .some(propertyOfClass) = ...` inserts a `self.` in front of `propertyOfClass` if it is indeed a property of the class. I'll try to find a fix for this, but this looks harder than #418
=> added test for self-insert in case let

CommandLineTool/main.swift
I didn't spot a good place for adding a test, since this is sort of the glue code for main.swift. If you point me to it I can add a test case, too.
Fixes nicklockwood/SwiftFormat#429
=> Fix extra newline when printing content to stdout

Sources/Arguments.swift, Sources/Options.swift, Tests/ArgumentsTests.swift, Tests/XCTestManifests.swift
Currently the enhanced `fileHeader` rule (`{file}`, `{created}` and `{created.year}`) is broken. 
This is because the `FileInfo` was lost when mutating the `Options`.
This PR keeps the `FileInfo` when merging arguments and adds a test for it.
=> Fixes enhanced `fileHeader` rule

Sources/Rules.swift, Tests/RulesTests.swift
First of all, thanks for making this nice tool! 
We ran it on our repo and found the build was broken, and thus sent a similar fix following 7eaf6859066d0b270723f5b8633e03f732e5b3cb.
=> Fixed `redundantObjc` rule for fileprivate members

Sources/Rules.swift, Tests/RulesTests.swift
Better handling of wrapped enums to avoid changing indentation of multiline `if case let` and similar scenarios where `case` appears above the current linebreak.
Includes an assertion that would have failed prior to the code change.
=> bugfix - xcode indentation breaks `if case let` indentation

Sources/CommandLine.swift
Fixes #476. 32ba97d added a new case `raw` to handle the non-EOL-appended output. However, this new case isn't bypassed for `--quiet` like `.content` was, leading to potential output issues.
=> Fix --quiet preventing .raw output

Sources/CommandLine.swift, Sources/Formatter.swift, Sources/Inference.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Sources/SwiftFormat.swift, Sources/Tokenizer.swift, Tests/FormatterTests.swift, Tests/MetadataTests.swift, Tests/SwiftFormatTests.swift, Tests/TokenizerTests.swift
I added some modifications which prints Xcode-compatible warning info and succeeded to use it in Xcode run phase before compilation:
@nicklockwood, These modifications are not ready for publishing in their current form, I think. As naming is not sophisticated in the proof-of-concept commits and many `.map { }` usage might be unnecessary but the main idea is acceptable, I think. And still the performance/run time is ok.
I count the line numbers in Tokenizer's `parseLineBreak()` and added the current line number to each token. Column info also would be fine.
=> Xcode output for  for --lint option

Rules.md
I don't think it was intended to change an IBOutlet to an IBAction.
=> Documentation fix: redundantObjc example code

README.md
This PR changes the Xcode Build phase install instructions to use Swift Package manager instead of Cocoapods 👍 
- all changes are to the README instructions, no source changes necessary
Note:
- first build after installation takes a while as the repository is cloned and then built
- After first build it knows to use the existing build. This will be retained even with Xcode's `Clean Build Folder` as the built version is kept within the `BuildTools` folder
- There is a commented line in the build phase script that instructs SPM to grab the latest version and rebuild if updated.
=> Use SPM for Xcode Build Phase

Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests.swift
This PR fixes an issue where the wrapping of color literals produces an unexpected behavior in XCode
Result:
=> Disables wrap parameters for image and color literals due to Xcode bug

Sources/ParsingHelpers.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
Fixed Issues https://github.com/nicklockwood/SwiftFormat/issues/570 .
Unit test is also added.
=> Fixed bug in `indexOfLastSignificantKeyword()` logic

README.md
There is a bug in the current git `pre-commit` hook. It tries to format files end with `swift`. For instance: `rswift` is a binary file and shouldn't be formatted.
Too test out:
```
echo rswift | grep -e '\(.*\).swift$' 
echo rswift | grep -e '\.swift$' 
```
I've also simplified the regex :)
=> Update hook for format only ".swift" files

Sources/Formatter.swift, Sources/ParsingHelpers.swift, Tests/FormatterTests.swift, Tests/ParsingHelpersTests.swift, Tests/XCTestManifests.swift
In this PR, https://github.com/nicklockwood/SwiftFormat/issues/577 will be solved by speeding up with cache.
Unit test is also added.
The following is the result of executing SwiftFormat with the sample code described in https://github.com/nicklockwood/SwiftFormat/issues/577#issuecomment-599522922.
<details close>
<summary>sample code</summary>
<br>
```swift
enum ManagersAssembly {
// swiftlint:disable:next closure_body_length
static let container: DependencyContainer = {
let container = DependencyContainer()
// MARK: - Cocoa
container.register {
UserDefaults.standard
}
container.register { _ -> JSONDecoder in
let jsonDecoder = JSONDecoder()
jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase
jsonDecoder.dateDecodingStrategy = .secondsSince1970
return jsonDecoder
}
container.register …
```
=> Fixed the cause of not performing `indexOfLastSignificantKeyword()` logic

Sources/Rules.swift, Tests/RulesTests.swift
```swift
enum Foo: String {
case `as` = "as"
case bs = "bs"
}
```
Currently, `redundantBackticks` will correctly strip the `"bs"` rawValue but will miss the `"as"`.
```swift
enum Foo: String {
case `as` = "as"
case bs
}
```
But the escaped `as` is also safe to cleanup.
This PR changes the token comparison to consider the unescaped value of the string to fix the issue.
```swift
enum Foo: String {
case `as`
case bs
}
```
=> redundantBackticks: Remove redundant raw values for escaped reserved words

README.md
In Xcode 11.4, it appears that changes to Swift Package Manager require an empty target, and at least one Swift file in order to run correctly. See the comments at https://blog.apptekstudios.com/2019/12/spm-xcode-build-tools/.
This PR adds the extra instructions necessary to get SwiftFormat running on Xcode 11.4 and above, using the SPM and Xcode build phases method.
=> Update Swift Package Manager instructions

Sources/ParsingHelpers.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
Fixed an indentation issue that occurred in 0.44.8 and later.
```
if foo {
bar()
.baz()
}
foo
.bar {
baz()
}.bar {
baz()
}
```
```
if foo {
bar()
.baz()
}
foo
.bar {
baz()
}.bar {
baz()
}
```
```
if foo {
bar()
.baz()
}
foo
.bar {
baz()
}.bar {
baz()
}
```
=> Fixed an indentation issue that occurred in 0.44.8 and later.

README.md
This was a little frustrating for me to track down as when it happens there is no feedback anywhere and no good way to troubleshoot as you might not notice the problem for a while after you added the script, so I thought I’d save the frustration to the next person.
This change updates the pre-commit hook instructions in the readme to use git-format-staged to allow formatting of partially staged files without losing the state of the index and unintentionally commit changes.
I considered keeping both instructions with a warning about the original one causing this issue but I think it’s better to just give working instructions.
Another alternative that doesn't require an external dependency would be to make it so the commit fails if any reformatting is performed (like lint but without the …
=> Update instructions for git pre-commit hook

Sources/ParsingHelpers.swift, Tests/CommandLineTests.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
This PR updates the `wrapArguments` rule to make sure internal and external parameter labels stay on the same line.
- This is an enhancement related to #664
Example:
```swift
// Before
func foo(with
bar: Int, and
baz: String
) -> LongReturnType {}
// After formatting with `wrapArguments --beforeFirst`
func foo(
with bar: Int,
and baz: String
) -> LongReturnType {}
// After formatting with `wrapArguments --afterFirst`
func foo(with bar: Int, 
and baz: String) -> LongReturnType {}
=> Keep internal / external parameter labels on the same line

SwiftFormat.xcodeproj/project.pbxproj
XcodeKit.framework needs embedding to work with Xcode 12 and  Big Sur.
According to the release notes, it is now required to build extensions with Xcode 12 - if you want to them to work on future versions of macOS (i.e. Big Sur and later).
From the release notes:
> For compatibility with new security features in macOS 11, Xcode extensions must be built using Xcode 12 and must embed XcodeKit.framework. An Xcode extension rebuilt with these tools remains compatible with older versions of Xcode and macOS. (51822755)
=> Xcode 12 on macOS 11 support

Rules.md, Sources/Rules.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
Reviewing changes within big enum declarations can be quite messy and hard to follow:
```diff
enum Enum1: Int {
-   case a = 0, p = 2, c, d
+   case a = 0, p = 4, c, f
case e, k
case m(String, String)
}
```
This PR adds a rule to rewrite enum declaration cases into one case per line. As you can see in the added test, it will go from this:
```swift
enum Enum1: Int {
case a = 0, p = 2, c, d
case e, k
case m(String, String)
}
```
to this:
```swift
enum Enum1: Int {
case a = 0
case p = 2
case c
case d
case e
case k
case m(String, String)
}
```
Improving the visibility of further changes in the enum declaration
```diff
enum Enum1: Int {
case a = 0
-    case p = 2
+    case p = 4
case c
case d
-    case e
+    case f
case k
case m(String, String)
```
- The name of the rule can probably be …
=> Add rule for multiline enum cases

Tests/RulesTests.swift
While testing another rule, I've found out that the current implementation of `multilineEnumCases` does not work for nested enums. I am adding a test that exposes the bug.
When running the rule to this code:
```swift
enum SearchTerm {
case term(name: String)
case category(category: Category)
enum CodingKeys: String, CodingKey {
case name
case type
case categoryId = "category_id"
case attributes
}
}
```
You end up with this:
```swift
enum SearchTerm {
case term(name: String)
case category(category: Category)
enum CodingKeys: String
case CodingKey 
case name
case type
case categoryId = "category_id"
case attributes
}
}
```
A workaround in the meantime would be to add the 2nd enum in an extension:
```swift
enum SearchTerm {
case term(name: String)
case category(category: Category)
} …
```
=> [Bug] Nested enums breaks with multiline cases

Sources/Rules.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
This is a follow-up to https://github.com/nicklockwood/SwiftFormat/pull/708#discussion_r475934954 that updates the new `organizeDeclarations` (#701) rule to handle struct computed properties correctly.
=> Update organizeDeclarations to handle struct computed properties correctly

Sources/Rules.swift, Tests/RulesTests.swift
This PR updates the `organizeDeclarations` rule to support `class` properties, as discussed in https://github.com/nicklockwood/SwiftFormat/pull/701#issuecomment-680323799
=> Update organizeDeclarations rule to support class properties

Sources/Rules.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
This PR fixes an issue where the new `organizeDeclarations` rule (#701) would inadvertently move comments at the end of one section to the start of the following section:
```diff
struct Foo {
// MARK: Lifecycle
init() {}
-   // Important comment at end of section!
-
// MARK: Public
+
+   // Important comment at end of section!
public let bar = 1
}
```
=> Fix issue where organizeDeclarations rule would inadvertently move comments at the end of a section

EditorExtension/Extension/FormatFileCommand.swift, EditorExtension/Extension/FormatSelectionCommand.swift
After formatting a file or selection in Xcode 12, the cursor position is lost and gets moved to the end of the file.
The problem is that this line always returns an empty array when the extension is used in Xcode 12:
```swift
let selections = invocation.buffer.selections.copy() as? [XCSourceTextRange] ?? []
```
Using `compactMap` to generate a typed copy of the selections resolves the issue.
=> Xcode Extension - Fixes restoring of selections in Xcode 12

Sources/Rules.swift, Tests/RulesTests.swift
This PR fixes an issue where the `openDeclarations` rule (#701) would accidentally parse `open` declarations as `internal` declarations:
```diff
open class Foo {
-    // MARK: Open
+    // MARK: Internal
open func bar() {}
}
```
=> Update organizeDeclarations rule to parse open declarations properly

Sources/Rules.swift
This `print("")` statement is printing a bunch of newlines while running the formatter (#721)
```
cal@Cals-MacBook-Pro Sample % swiftformat .  
Running SwiftFormat...
warning: No Swift version was specified, so some formatting features were disabled. Specify the version of Swift you are using with the --swiftversion option, or by adding a .swift-version file to your project.
SwiftFormat completed in 0.2s.
49/49 files formatted.
```
```
cal@Cals-MacBook-Pro Sample % swiftformat .                
Running SwiftFormat...
warning: No Swift version was specified, so some formatting features were disabled. Specify the version of Swift you are using with the --swiftversion option, or by adding a .swift-version file to your project.
SwiftFormat completed in 0.19s.
49/49 files formatted.
```
=> Clean up print statement that prints newlines while formatting

Sources/Arguments.swift, Sources/Rules.swift, Tests/RulesTests.swift
This PR makes a few improvements to the `organizeDeclarations` rule (#701) based on discussions from airbnb/swift#102:
- Correct misspelled mark comments (instead of duplicating them) by comparing the edit distance
- Group `typealias` declarations with types instead of with properties 
- Previously they were being treated as `instanceProperty` declarations, but they are actually more type-like)
- Stop inserting blank lines at the top and bottom of type bodies
- This resolves linting conflicts with the `blankLinesAtEndOfScope` rule
=> More organizeDeclarations improvements

Sources/Rules.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
Previously, the `organizeDeclarations` rule (#701) was validating all comments within a type body. This would mangle a type that had a matching comment inside a function body (#725).
Now we validate that the comment sits at the top level of a type body before we try to update it to the correct category separator. This fixes #725.
=> Update organzieDeclarations rule to only validate comments at the top level of a type body

README.md
Related: https://github.com/nicklockwood/SwiftFormat/issues/730
Test:
Ex: `/my/file path with spaces/file.swift`
=> Update pre-commit hook to work with spaces in file path

Rules.md, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/RulesTests+Organization.swift, Tests/XCTestManifests.swift
The PR adds support for organizing the body of `extension` declarations with `organizeDeclarations`.
This is optional, since you'd probably only want to do this if you're using the `extensionAccessControl` rule (#742), and configurable using the new `--organizetypes` option.
=> Add extension support to organizeDeclarations

Sources/FormattingHelpers.swift, Tests/RulesTests+Organization.swift, Tests/XCTestManifests.swift
This PR fixes an issue where the new `extensionAccessControl` rule (#742) would place visibility keywords before annotations. This fixes #757.
```diff
-public extension Foo {
+extension Foo {
-    @discardableResult
+    public @discardableResult
func bar() {}
}
```
```diff
-public extension Foo {
+extension Foo {
@discardableResult
-    func bar() {}
+    public func bar() {}
}
```
=> Fix issue where extensionAccessControl would place visibility keywords before annotations

Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Organization.swift, Tests/XCTestManifests.swift
This PR fixes two more issues with the new `markTypes` rule (#747):
- Fixes an issue where marks would be incorrect when following another extension of the same type:
```diff
// MARK: Foo + BarProtocol
extension Foo: BarProtocol {}
-// MARK: QuuxProtocol
+// MARK: Foo + QuuxProtocol
extension Foo: QuuxProtocol {}
```
- Update the marks to use the entire fully-qualified name
```diff
-// MARK: Foo + BarProtocol
+// MARK: MyModule.Foo + MyModule.MyNamespace.BarProtocol
extension MyModule.Foo: MyModule.MyNamespace.BarProtocol {}
```
=> More markTypes fixes and improvements

Rules.md, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/RulesTests+Wrapping.swift, Tests/XCTestManifests.swift
This PR adds a `--wrapconditions` option to the wrapArguments rule as discussed in #772. This lets users choose between the two following wrap styles for multiline control flow statements:
```swift
if let foo = foo,
let bar = bar {}
guard let foo = foo,
let bar = bar else {}
```
```swift
if 
let foo = foo,
let bar = bar {}
guard 
let foo = foo,
let bar = bar else {}
```
=> Add --wrapconditions option

Sources/Rules.swift, Tests/RulesTests.swift, Tests/XCTestManifests.swift
If `endIndex == formatter.tokens.endIndex`, 
```swift
formatter.tokens[lastHeaderTokenIndex + 1 ... endIndex]
```
could crash.
=> Fix a potential index out of range crash

Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Tests/RulesTests+Wrapping.swift, Tests/XCTestManifests.swift
This PR adds some fixes and improvements for the new `--wrapconditions` rule added in #775
1. The command line option didn't work because the `OptionDescriptor` was using the wrong keypath
2. Fixed some instances where `--wrapconditions` was adding unnecessary newlines
=> --wrapconditions fixes and improvements

README.md
Since calling `brew cask upgrade` is deprecated, now we use `brew upgrade --cask` instead.
=> Update source editor extension upgrade command

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
Addresses #816 by adding options for `inferred` and `explicit` to Redundant Type rule
=> Redundant type -- add explicit type option

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
I noticed that the current implementation of `--redundanttype explicit` is too greedy if it encounters static or class members/funcs. This PR should help this rule better handle these cases.
=> Better handle Redundant Type static or class members/funcs

Sources/Arguments.swift, Tests/ArgumentsTests.swift, Tests/XCTestManifests.swift
Currently, in the configuration file, if a comment follows a line continuation character, the comment and all the subsequent lines are ignored. This should be considered a bug. 
With this change the parser just ignores the comments, but not the lines which follow after the comment. So the continuation only applies to the first line after the continuation character which is not a comment.
=> Ignore comments in lines connected by a continuation character

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
The `explicit` option of the redundanttype rule is still a bit too eager — it will remove "redundant" types, moving to `.init` style even for Optional binding, which will fail to compile. This breaks early if it's discovered that the current `let/var` token is from Optional binding.
=> Exit early if redundanttype is from Optional binding

README.md
Homebrew recently disabled `brew cask install` in favor of `brew install --cask`. It was deprecated in 2.6.0 (release notes [here](https://brew.sh/2020/12/01/homebrew-2.6.0/) and disabled in 2.7.0.
=> Update swiftformat-for-xcode install instructions

Sources/FormattingHelpers.swift, Tests/RulesTests+Wrapping.swift, Tests/XCTestManifests.swift
This PR fixes a bug where `--wrapreturntype if-multiline` would unexpectedly wrap a single-line method that follows a multi-line array declaration
```swift
final class Foo {
private static let array = [
"one",
]
private func singleLine() 
-> String 
{}
}
```
```swift
final class Foo {
private static let array = [
"one",
]
private func singleLine() -> String {}
}
```
=> Fix issue where single line method after array would wrap unexpectedly

.gitignore, Sources/Arguments.swift, Sources/CommandLine.swift, Sources/Formatter.swift, Sources/JSONReporter.swift, SwiftFormat.xcodeproj/project.pbxproj
Fix for https://github.com/nicklockwood/SwiftFormat/issues/890
The JSON format is inspired by the format of SwiftLint JSON reporter
=> [Feature] Add support for JSON output

Rules.md, Sources/Rules.swift, Sources/Tokenizer.swift, Tests/RulesTests+Indentation.swift, Tests/RulesTests+Wrapping.swift, Tests/TokenizerTests.swift, Tests/XCTestManifests.swift
On our team we wrap arguments / parameters that reach a certain length (120 char). While editing, I find it really tedious to go through and move them to their own lines, but at the same time it's much more soothing to my mind to newline them before replacing the tokens. Especially if the method signature contains a callback or more. 
Enter SwiftFormat for Xcode. _Almost_. Turns out it didn't parse Xcode placeholder tokens, so it couldn't wrap things for me until I filled them out.
So I added support for recognizing placeholder tokens, along with a few tests.
I could probably update the implementation to do less index work, and keep that control statement more high level, but I wanted to see if this is even a thing anyone else wants.
=> Adds support for tokenizing Xcode placeholder tokens

Sources/Arguments.swift
I created an extension that uses SwiftFormat successfully.
However, I needed to use `@testable import SwiftFormat` to access some of the internal methods. Now when I try to Archive the project, it complains about the `@testable import`: `Module 'SwiftFormat' was not compiled for testing`.
The `internal` methods that required the `@testable import` were all in the Arguments.swift file:
1. parseConfigFile
2. rulesFor
3. formatOptionsFor
By exposing these three methods, I should be able to get rid of the `@testable`, and use SwiftFormat in an Xcode Source Editor Extension.
```
@testable import SwiftFormat
private func runSwiftFormat(subject: String, swiftFormatFilename: String) throws -> String {
let swiftFormatConfig = try FileSyncManager.readFileContents(filename: swiftFormatFilename)
let …
```
=> Make functions public to support creating an Xcode Extension

Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Wrapping.swift, Tests/XCTestManifests.swift
This PR adds `wrapMultilineStatementBraces` support to more types of multiline statements
```
UIView.animate(
duration: 10,
options: []) {
print()
}
var items: Adaptive<CGFloat> = .adaptive(
compact: Sizes.horizontalPaddingTiny_8,
regular: Sizes.horizontalPaddingLarge_64) {
didSet { updateAccessoryViewSpacing() }
}
```
```
UIView.animate(
duration: 10,
options: []) 
{
print()
}
var items: Adaptive<CGFloat> = .adaptive(
compact: Sizes.horizontalPaddingTiny_8,
regular: Sizes.horizontalPaddingLarge_64) 
{
didSet { updateAccessoryViewSpacing() }
}
```
=> Add wrapMultilineStatementBraces support for more cases

README.md
In Xcode 13 using `SDKROOT=macosx` will generate a warning: `no such SDK: macosx`.  This can be fixed by updating the Build Phase to use the following instead:
`SDKROOT=(xcrun --sdk macosx --show-sdk-path)`
This should allow `xcrun` to dynamically fetch the SDK path instead.  This pull request simply updates the README with that change.
Thanks to @kishikawakatsumi for the [tip](https://twitter.com/k_katsumi/status/1431574995445026824).
Closes #1009
=> Update README Instructions for Build Phase SDKROOT

Rules.md, Sources/Examples.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Redundancy.swift
This PR adds a `--redundanttype infer-locals-only` option that uses `inferred` for local properties within method bodies (etc) but uses `explicit` for globals or instance properties.
```diff
class Foo {
-     let view: UIView = UIView()
+     let view: UIView = .init()
func method() {
-         let view: UIView = UIView()
+         let view = UIView()
}
}
```
This is because type checking for globals and type properties using inferred types can be more expensive: https://twitter.com/uint_min/status/1441448033988722691?s=21
=> Add --redundanttype infer-locals-only option

Rules.md, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/RulesTests+Organization.swift
This PR adds a `--markcategories` option for the `organizeDeclarations` rule, which configures whether or not to insert `// MARK:` comments between categories.
```swift
class Foo {
private func privateMethod() {}
private let bar = 1
public let baz = 1
}
```
```swift
class Foo {
// MARK: - Public
public let baz = 1
// MARK: - Private
private let bar = 1
private func privateMethod() {}
}
```
```swift
class Foo {
public let baz = 1
private let bar = 1
private func privateMethod() {}
}
```
=> Add --markcategories true/false option for organizeDeclarations rule

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR fixes an issue where the `redundantInit` failure could cause a build failure if the `.init` and open paren aren't on the same line. This seems to be because parsing for method calls / `.init` is more lenient than parsing for the sugared initializer syntax.
```swift
var foo: Foo {
Foo.init
(
bar: bar,
baaz: baaz
)
}
```
```swift
var foo: Foo {
Foo          // 🛑 expected member name or constructor call after type name
(
bar: bar,
baaz: baaz
)
}
```
```swift
var foo: Foo {
Foo(
bar: bar,
baaz: baaz
)
}
```
=> Fix issue where redundantInit rule could cause build failure

Rules.md, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/RulesTests+Syntax.swift, Tests/RulesTests+Wrapping.swift
This PR adds a new `--wraptypealiases` option, that supports both `beforeFirst` and `afterFirst` wrapping.
----
At Airbnb, our DI system uses "provider" protocols. Features/components typically express their dependencies as a `typealias` containing all of the types that they need to access. For example:
```swift
typealias Dependencies = FooProviding & BarProviding & BaazProviding & QuuxProviding
// then later you can do `dependencies.foo`, `dependencies.bar` etc -- it's quite nice!
```
The current `wrap` implementation inserts the minimum number of newlines necessary to make the declaration fit within the line limit. For example:
```swift
typealias Dependencies = FooProviding & BarProviding & BaazProviding 
& QuuxProviding
```
We typically prefer wrapping so that each type is on a …
=> Add --wraptypealiases option

Rules.md, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/RulesTests+Wrapping.swift
This PR improves wrapping for ternary operators. This implements #888.
Previously, ternary operators were wrapped the minimum number of times to fit them within the limit.
```swift
// For example, if slightly over the length limit, this:
let foo = fooCondition ? longValueThatContainsFoo : longValueThatContainsBar
// would be wrapped to:
let foo = fooCondition ? longValueThatContainsFoo : 
longValueThatContainsBar
```
Now, ternary operators wrap intelligently at both the `?` and `:`:
```swift
// For example, if slightly over the length limit, this:
let foo = fooCondition ? longValueThatContainsFoo : longValueThatContainsBar
// is now wrapped to:
let foo = fooCondition 
? longValueThatContainsFoo 
: longValueThatContainsBar
```
=> Improve wrapping for ternary operators

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Spacing.swift, Tests/RulesTests+Syntax.swift
This PR updates `redundantVoidReturnType` to apply to closures as well
e.g. 
```swift
{ foo -> Void in foo() }
```
becomes
```swift
{ foo in foo() }
```
I notice this seemed to be intentionally not supported in the existing implementation (there was a `testNoRemoveRedundantVoidInClosureArguments()` test case testing that this didn't happen). Was this just a regression test for the existing behavior, or was this an intentional design decision / style preference? I [checked on swiftfiddle.com](https://swiftfiddle.com/?c=H4sIAAAAAAAAA6tWSlayUspJLVFIy89XsFWoVtAAMqwUgkuKMvPSNRUy8xQKgKwSkKimQm1MXkwekKURo5SRmpOTH6OkqaSjVAY0wUjPSKkWAD6BO55NAAAA) and the examples with `-> Void` removed compile successfully in all Swift versions (back to 2.2). 
We could add an option for this if you don't think it …
=> Update redundantVoidReturnType to apply to closures

Sources/Rules.swift, Tests/RulesTests+Wrapping.swift
This PR improves the indentation of wrapped ternary operators (when using `--wrapternary before-operators`)
```swift
let ternary = condition
? values
.map { $0.bar }
.filter { $0.hasFoo }
.last
: otherValues
let foo = fooCondition
? barCondition
? longTrueBarResult
: longFalseBarResult
: baazCondition
? longTrueBaazResult
: longFalseBaazResult
```
```swift
let ternary = condition
? values
.map { $0.bar }
.filter { $0.hasFoo }
.last
: otherValues
let foo = fooCondition
? barCondition
? longTrueBarResult
: longFalseBarResult
: baazCondition
? longTrueBaazResult
: longFalseBaazResult
```
=> Improve indentation of wrapped ternary operators

Sources/Rules.swift, Tests/RulesTests+Syntax.swift
The PR fixes an issue where the `--indentstrings true` mutliline string indentation would conflict with the `trailingSpace` rule if the multiline string had a blank line.
=> Fix issue where multiline string indentation conflicted with trailingSpace rule

Sources/Rules.swift, Tests/RulesTests+Wrapping.swift
This PR fixes a regression introduced in #1071 where braces of throwing methods would wrap incorrectly
```swift
func method(
foo: Int,
bar: Int) throws {
print("function body")
}
```
```swift
func method(
foo: Int,
bar: Int) throws 
{
print("function body")
}
```
----
I also fixed a regression (also introduced in #1071) where trailing closure braces could be wrapped incorrectly:
```swift
guard foo else {
return
}
when(fulfilled: promise)
.then 
{
// chained closure body 1
}
.done 
{
// chained closure body 2
}
```
```swift
guard foo else {
return
}
when(fulfilled: promise)
.then {
// chained closure body 1
}
.done {
// chained closure body 2
}
```
=> Fix brace wrapping regression for throwing methods

Sources/ParsingHelpers.swift, Sources/Rules.swift, Sources/SwiftFormat.swift, Tests/ArgumentsTests.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Organization.swift
The `--modifierorder` option does not currently recognize these two modifiers (documented at https://docs.swift.org/swift-book/ReferenceManual/Declarations.html#grammar_declaration-modifiers).
=> Add support for the `unowned(safe)` and `unowned(unsafe)` modifiers in `--modifierorder`.

.github/workflows/build.yml, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This fixes two issues:
1. The following comment no longer causes an assertion failure in the `redundantSelf` rule:
```swift
/*
asdf
*/
```
2. A multiline comment with a nonzero indent and at least 7 lines long is no longer only partially rewritten:
Input:
```swift
/*
One
Two
Three
Four
Five
Six
Seven
*/
```
Output (before):
```swift
// One
// Two
// Three
// Four
// Five
// Six
Seven
```
Output (after):
```swift
// One
// Two
// Three
// Four
// Five
// Six
// Seven
```
=> Add missing `endIndex` handling in `blockComments` rule implementation

EditorExtension/Application/SwiftFormatter.entitlements, EditorExtension/Extension/FormatFileCommand.swift, EditorExtension/Extension/FormatSelectionCommand.swift, EditorExtension/Extension/LintFileCommand.swift, EditorExtension/Extension/ProjectConfigurationFinder.swift, EditorExtensionXPCService/ConfigurationFinderService.swift, EditorExtensionXPCService/ConfigurationFinderServiceProtocol.swift, EditorExtensionXPCService/Info.plist, EditorExtensionXPCService/ServiceDelegate.swift, EditorExtensionXPCService/main.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/SwiftFormatTests.swift
Related: #1108 
Happy new year.
I added a new target EditorExtensionXPCService to call AppleScript to get the folder path of the current opening project.
It then searches upwards for a .swiftformat file, parses it, and sends it back to the extension. If the file is not found, we can fall back to using the in-app configuration.
One small issue is that AppleScripts may take 3-4 seconds to compile (or maybe warm-up?) after we run a command on the extension. But luckily, it only happens once until Xcode is quit and relaunched.
=> Use project-specific configuration in Xcode extension

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR fixes an issue where the `redundantClosure` rule could break the build for certain `Void`-returning closures. This fixes the issue [discussed here](https://github.com/nicklockwood/SwiftFormat/issues/1096#issuecomment-1012231386).
Previously, this closure:
```swift
lazy var triggerSomething: Void = {
logger.trace("log some stuff before Triggering")
TriggerClass.triggerTheThing()
logger.trace("Finished triggering the thing")
}()
```
was incorrectly being removed and reformatted to: 
```swift
lazy var triggerSomething: Void = logger.trace("log some stuff before Triggering")
TriggerClass.triggerTheThing()
logger.trace("Finished triggering the thing")
```
=> Fix issue where redundantClosure rule could break build for certain Void closures

Rules.md, Sources/Examples.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Indentation.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Syntax.swift
This PR adds a new rule implementation to capture `self` explicitly to enable implicit `self` in closure bodies (from [SE-0269](https://github.com/apple/swift-evolution/blob/main/proposals/0269-implicit-self-explicit-capture.md), added in Swift 5.3).
When this rule is enabled, by default it only applies to closures that use explicit `self` repeatedly (e.g. more than once).
```swift
DispatchQueue.main.async {
self.performFoo()
self.performBar()
self.performBaaz()
}
```
```swift
DispatchQueue.main.async { [self] in
performFoo()
performBar()
performBaaz()
}
```
On the other hand, this example is unchanged by default:
```swift
DispatchQueue.main.async {
self.performFoo()
}
```
but with `--selfcount 1` it would be changed to:
```swift
DispatchQueue.main.async { [self] in
performFoo()
}
```
=> Add rule to capture self explicitly to enable implicit self in closure body

CommandLineTool/main.swift, Sources/CommandLine.swift
Fixes #990
Switched out glibc for ucrt on Windows. Unsure of how compatible it is, but all the tests pass and the tool has worked fine for my needs.
There are some compiler warnings which I am unsure of how to resolve:
1. >  warning: 'isatty' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _isatty.
This can be ignored with the compiler option `/D_CRT_NONSTDC_NO_WARNINGS`, but I don't know how to pass compiler options using Swift. Alternatively I could use compiler directives to switch to `_isatty` when it's Windows, but I think it'd be nicer to just ignore it if possible.
2. > lld-link: warning: SwiftFormat\.build\x86_64-unknown-windows-msvc\release\CommandLineTool.build\main.swift.o: locally defined symbol imported: …
=> Support Windows

Sources/Rules.swift, Tests/RulesTests+Organization.swift
Problem:
trying to format
```swift
// swiftformat:sort
enum Test {
case only
}
```
crashes with
```
$ swiftformat test.swift 
Running SwiftFormat...
Reading config file at <Redacted>/.swiftformat
[1]    88603 trace trap  swiftformat test.swift
```
The workaround is obvious if you know the cause (remove the annotation from single-case enums), but I think we should avoid the crash.
=> Avoid crashing when trying to sort an enum that has only one case

Sources/CommandLine.swift
This is my first time contributing here, but the fix felt easy enough. This may constitute a test, but I don't yet know how to mock the OS version during Swift tests. I also felt the fix was insignificant enough to go directly to develop. Help and commentary welcome.
Fixes #1158
=> Fixed os availability error (issue #1158)

Rules.md, Sources/Examples.swift, Sources/Rules.swift, Sources/SwiftFormat.swift, Tests/RulesTests+Redundancy.swift
This PR adds a new `redundantOptionalBinding` for Swift 5.7+ that applies the new shorthand optional binding syntax added in [SE-0345](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md) (😄)
```diff
- if let foo = foo {
+ if let foo {
print(foo)
}
- guard let self = self else {
+ guard let self else {
return
}
```
=> [SE-0345] Add redundantOptionalBinding rule for Swift 5.7+

Rules.md, Sources/Examples.swift, Sources/Rules.swift, Tests/RulesTests+Linebreaks.swift, Tests/RulesTests.swift
Summary:
Add blankLineAfterImports rule which insert a blank line after imports statements.
Test Plan:
Add unit tests and run all tests.
=> add  `blankLineAfterImports`

Rules.md, Sources/Examples.swift, Sources/Formatter.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR adds a new `opaqueGenericParameter` rule that updates generic methods to use Swift 5.7's new simpler syntax where possible / equivalent. For example:
```diff
- func handle<T: Fooable>(_ value: T) {
+ func handle(_ value: some Fooable) {
print(value)
}
- func handle<T>(_ value: T) where T: Fooable, T: Barable {
+ func handle(_ value: some Fooable & Barable) {
print(value)
}
- func handle<T: Collection>(_ value: T) where T.Element == Foo {
+ func handle(_ value: some Collection<Foo>) {
print(value)
}
```
=> Add new rule to update generic methods to use opaque generic parameter syntax where equivalent

Scripts/get-version.sh, Scripts/spm-artifact-bundle.sh, Scripts/spm-macos-artifact-bundle-info.template
* Add a script to 'Scripts' to get the current SwiftFormat version 'get-version.sh'.
* Add a script to 'Scripts' to build an SPM artifact bundle to attach to a release 'spm-artifact-bundle.sh'.
Closes #1213.
=> Create script to create an SPM artifact bundle

Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR updates the `opaqueGenericParameters` rule to handle generic return types properly.
Previously it just didn't parse return types at all, so it would do silly things like:
```swift
// Before
func foo<T: Fooable>(_ value: T) -> T { ... }
// After
func foo(_ value: some Fooable) -> T { ... } // oops!
```
Return types are also special, because `some Fooable` in a parameter position is different from `some Fooble` in a return position ([SE-244](https://github.com/apple/swift-evolution/blob/main/proposals/0244-opaque-result-types.md)). In `-> T where T: Fooable`, the generic type is caller-specified, but with `-> some Fooable` the generic type is specified by the function implementation. Because those represent different concepts we can't convert between them.
Now the signature of this …
=> Update `opaqueGenericParameters` rule to handle generic return types properly

Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR fixes #1221, so these `typeSugar`ed extensions no longer cause an assertion failure:
```swift
extension [Foo] {}
extension Foo? {}
extension [Foo: Bar] {}
extension [[Foo: [Bar]]]? {}
```
=> Fix assertion after applying typeSugar rule to array/dictionary extensions

Rules.md, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR adds a new `genericExtensions` rule, implementing support for the new extension syntax added in Swift 5.7 by [SE-0361](https://github.com/apple/swift-evolution/blob/main/proposals/0361-bound-generic-extensions.md).
```diff
- extension Array where Element == Foo {}
- extension Optional where Wrapped == Foo {}
- extension Dictionary where Key == Foo, Value == Bar {}
- extension Collection where Element == Foo {}
+ extension Array<Foo> {}
+ extension Optional<Foo> {}
+ extension Dictionary<Key, Value> {}
+ extension Collection<Foo> {}
// With `typeSugar` also enabled:
- extension Array where Element == Foo {}
- extension Optional where Wrapped == Foo {}
- extension Dictionary where Key == Foo, Value == Bar {}
+ extension [Foo] {}
+ extension Foo? {}
+ extension [Key: Value] {}
// …
```
=> Add `genericExtensions` rule for SE-0361

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR fixes an issue where the `redundantClosure` rule would break the build for `Void` closures calling `@discardableResult` functions. Fixes #1236.
=> Fix issue where `redundantClosure` rule would break build for `Void` closures calling `@discardableResult` functions

Sources/ParsingHelpers.swift, Sources/Rules.swift, Sources/Tokenizer.swift, Tests/RulesTests+Indentation.swift
This PR fixes an issue where a function with `async throws` was indented differently than a function with just `throws`. Fixes  #1242.
This was because `async` is parsed as an `identifier` but `throws` is parsed as a `keyword`, so the indent rule wasn't handling the `async` in the same way as it would handle `throws`. I tried updating the parser to treat `async` as a `keyword` instead, but this caused other test failures (since `async` is merely a context-specific keyword, unlike `throws`).
```swift
// before
func multilineFunction(
foo _: String,
bar _: String)
async throws -> String {}
// after
func multilineFunction(
foo _: String,
bar _: String)
async throws -> String {}
```
=> Fix issue where `async throws` was indented differently than just `throws`

Rules.md, Sources/Rules.swift, Tests/RulesTests+Wrapping.swift
This rule reformats single-line comments that exceed `--maxwidth` option value into multiple single-line comments.
E.g.
```swift
// a b cde fgh
```
is reformatted as
```swift
// a b
// cde
// fgh
```
if `--maxwidth` is set to 6 columns.
=> Add `wrapSingleLineComments` rule

Sources/Rules.swift, Tests/RulesTests+Indentation.swift
This PR fixes a regression caused by #1247 where a function argument label named `async:` would unexpectedly be indented.
```swift
func multilineFunction(
foo _: String,
async _: String)
-> String {}
```
```swift
func multilineFunction(
foo _: String,
async _: String)
-> String {}
```
=> Fix issue where function argument label named `async:` would unexpectedly be indented

.github/workflows/docker.yml, Dockerfile, README.md
Resolves #1067 
Newly "Create and publish a Docker image" action in this PR:
1. Is triggered on every tag push (`docker/metadata-action` uses this tag for Docker image metadata).
2. Builds arm64 and amd64 slices.
3. Publishes images to GitHub Packages linked to the repository.
4. Doesn't require any additional setup for this repo.
I "moved" the latest 0.49.16 tag in the source repo after my changes so you can see how it will look like [in the repo Packages section](https://github.com/vox-humana/SwiftFormat/pkgs/container/swiftformat)
Also, added a section to README file. Not sure whether I need to mention anything else, it just works 😄 
I don't know how the release process for this repo works, happy to adjust the action to make it easier if needed.
=> Add Docker image

Sources/FormattingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR fixes a bunch of edge cases with the `opaqueGenericParameters` rule. With these fixes, our app repo complies successfully after applying this rule.
=> Fix edge cases with `opaqueGenericParameters` rule

Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR updates the `docComments` rule to not convert SwiftLint annotations to doc comments, since SwiftLint expects these to be regular comments and not doc comments.
=> Update `docComments` rule to not convert SwiftLint annotations to doc comments

Sources/FormattingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR fixes #1269 and #1275, where the `opaqueGenericParameters` rule was causing build failures.
=> Fix bugs in `opaqueGenericParameters` rule

Sources/FormattingHelpers.swift, Tests/RulesTests+Syntax.swift
=> Fix crash in `opaqueGenericParameters` rule

Sources/FormattingHelpers.swift, Tests/RulesTests+Syntax.swift
This PR fixes #1281, which affected both `opaqueGenericParameters` and `genericExtensions`.
This specific bug was originally fixed in https://github.com/nicklockwood/SwiftFormat/pull/1260, but it looks like the fix was lost at some point (probably due to merge conflicts?)
=> Fix `parseGenericTypes` handling of constraints with their own generic types (e.g. `== Foo<Bar>`)

Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR updates the `opaqueGenericParameters` rule to apply to `init` declarations, as well as `func` declarations. Fixes #1291.
=> Update `opaqueGenericParameters` rule to apply to initializers

.swiftformat, Package@swift-5.6.swift, PluginTests/.gitignore, PluginTests/Package.swift, PluginTests/README.md, PluginTests/Sources/PackageUsingPlugin/NotFormattedFile.swift, PluginTests/test.sh, Plugins/SwiftFormatPlugin/Shared/CommandPlugin+Extension.swift, Plugins/SwiftFormatPlugin/Shared/PluginToolProviding.swift, Plugins/SwiftFormatPlugin/SwiftFormatPlugin.swift, Plugins/SwiftFormatPlugin/SwiftFormatPluginXcode.swift, README.md, Tests/SwiftFormatTests.swift
Adding implementation for a Swift Package command plugin. Resolves #1198 
The implementation was previously shipped in https://github.com/MarcoEidinger/SwiftFormatPlugin and tested by other developers.
The plugin is available for developers
- who are using Swift 5.6 (or higher) and
- added `SwiftFormat` package as a dependency to their package.
In the folder `PluginTests` such usage is demonstrated. The shell script `PluginTests/test.sh` allows manual verification that `PluginTests/Sources/PackageUsingPlugin/NotFormattedFile.swift` file can be formatted. In a subsequent pull request, the shell script could be leveraged to introduce CI verification (e.g. GitHub action).
I did not increase the minimum swift-tools-version and rely on [version-specific manifest …
=> Add Swift package command plugin

Rules.md, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/RulesTests+Wrapping.swift
This PR adds an option to wrap function effects (`throws`, `async`). This is helpful when using `closingParenOnSameLine: false`.
```swift
func multilineFunction(
foo _: String,
bar _: String)
async throws -> String {}
```
```swift
func multilineFunction(
foo _: String,
bar _: String) async throws 
-> String {}
```
=> Add option to wrap function effects (`throws`, `async`)

CHANGELOG.md, Rules.md, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This was discussed in more depth in issue #1139, where this rule in particular was not only causing several compiler errors but has also been proven to introduce subtle bugs into applications which may not be obvious or easy to diagnose at first look.
I think the value of this rule, even with it being opt-in, does not outweigh the risk to projects with it being turned on. As such, I believe this should be removed.
Alternative options may include a more prominent warning or description for the rule, or significant work on the rule itself to make it more resilient (but as this would essentially require knowledge of the source of every function called and whether that resides within the source code of the client) is rather impractical.
Closes #1139. @nicklockwood: this may be perceived as a …
=> Removed `preferDouble` rule

Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Sources/SwiftFormat.swift, Tests/RulesTests+Redundancy.swift
As of SE-0269 and SE-0365, implicit self is allowed in closures under certain circumstances. This PR updates the `redundantSelf` rule to use implicit self in closures that meet these requirements.
```diff
class Foo {
let bar: Int
func method() {
closure { [self] in
// self is already captured explicitly, so explicit self is not necessary:
-             print(self.bar)
+             print(bar)
}
}
}
```
```diff
struct Foo {
let bar: Int
func method() {
closure {
// self is a value type so capturing it is unlikely to produce a retain cycle:
-             print(self.bar)
+             print(bar)
}
}
}
```
```diff
class Foo {
let bar: Int
func method() {
closure { [weak self] in
guard let self else { return }
// self is already captured explicitly, so explicit self is not necessary:
- …
```
=> Update `redundantSelf` rule to use implicit self in eligible closures (SE-0269, SE-0365)

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR fixes another issue with #1303 that could cause the build to break, because we weren't parsing and handling parameter lists in closures that didn't also have a capture list. For example:
```diff
struct Foo {
var bar = "bar"
func method() {
closure { [self] bar in
-           self.bar = bar
+           bar = bar
}
}
}
```
=> Fix issue where `redundantSelf` ignored parameters in closures without capture list

CommandLineTool/main.swift, Sources/SwiftFormat.swift
Problem: when invoked from a directory such as `/var/tmp`, SwiftFormat will use the `/private/var/tmp` directory instead [as its working directory](https://github.com/nicklockwood/SwiftFormat/blob/ce821205ea1bb4de67817c2dbec99f881d0e50d4/CommandLineTool/main.swift#L84). It will then build all of the globs based on that directory and as a result of that, all exclusions/inclusions won't work because their `match(...)` will return `false`.
Solution: `/var` and `/private/var` on macOS [seems to be a big clusterfuck](https://stackoverflow.com/a/16026416/9316533), so assuming that Apple actually wants you to not use the real path (without symlinks), use the `standardizedFileURL` which kill `/private` part for us.
=> Standardize working directory path

README.md, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
Recently I've been seeing the warning detailed here https://github.com/nicklockwood/SwiftFormat/issues/1322
I've managed to easily fix it for this scenario:
```diff
var variable: Int {
switch self {
-   case let .a(_): // 'let' pattern has no effect; sub-pattern didn't bind any variables
+   case .a: 
return 0
case .b:
return 1
}
}
```
I've implemented it inside `redundantPattern` since it was already identified.
On the other hand, when `(_)` is not present it's not straightforward, so I am taking a little bit more time to work on that one. (`redundantLet` iterates over `"_"` and `redundantPattern` over `(`)
```diff
var variable: Int {
switch self {
-   case let .a: // 'let' pattern has no effect; sub-pattern didn't bind any variables
+   case .a:       
return 0
case .b:
return 1
} 
} …
```
=> feat: Removing let when pattern is redundant

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Spacing.swift
Option to customise spacing around data type delimiter based on https://github.com/nicklockwood/SwiftFormat/issues/1168#issuecomment-1361464823
=> feat: Data type spacing around delimiter

Rules.md, Sources/Examples.swift
Hello,
I just wanted to standardise the headers of a project. I figured out the tokens by looking at the SwiftFormat source. Maybe it is documented elsewhere, but having an example in the `Rules.md` would have been helpful for me, so here is this PR :)
=> 📝 Document `fileHeader` text tokens with example

EditorExtension/Application/Base.lproj/Main.storyboard
This PR updates the installation instructions in the about screen because System Preferences  UI was redesigned in macOS Ventura with a different organization Structure.
**Before** 
**After**
I also updated some autolayout settings to clear the warnings resulting from this change.
=> updated installation instructions for Xcode Source Editor Extensions

Sources/ParsingHelpers.swift, Tests/RulesTests+General.swift
I think headerdoc style comments should be preserved in `associatedtype` declarations. Otherwise it breaks the header documentation being rendered within Xcode documentation/help system.
```
/// An interesting comment about Foo.
associatedtype Foo
```
should be preserved, not changed to
```
// An interesting comment about Foo.
associatedtype Foo
```
I have updated the `isDeclarationTypeKeyword` function to include this keyboard. Unit tests all pass locally.
=> FIX: Protocol Associated Type Declaration support doc style comments

Rules.md, Snapshots/Consumer/Sources/Consumer.swift, Snapshots/Layout/Layout/LayoutLoader.swift, Snapshots/Layout/Layout/LayoutNode.swift, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR updates the `redundantReturn` and `redundantClosure` rules to support the new single-statement if / switch expression syntax added in [SE-0380](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md), which looks like it will be included in Swift 5.8.
```diff
func foo(_ condition: Bool) -> String {
if condition {
-         return "foo"
+         "foo"
} else {
-         return "bar"
+         "bar"
}
}
```
```diff
- let value = {
-     if condition {
-         return "foo"
-     } else {
-         return "bar"
-     }
- }()
+ let value = if condition {
+     "foo"
+ } else {
+     "bar"
+ }
```
I took these steps when working on this change, and you can review each of these changes individually by looking at the respective commit:
1. I factored …
=> Update `redundantReturn` and `redundantClosure` rules to support single-statement if / switch expressions (SE-0380)

Rules.md, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Sources/Tokenizer.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Syntax.swift
This PR adds a new `conditionalAssignment` rule and updates the `redundantType` rule to handle the if / switch expression assignment syntax added in Swift 5.8 (SE-0380).
This updates code using the following pattern:
```swift
let foo: Foo
if condition {
foo = Foo("foo")
} else {
foo = Foo("bar")
}
```
to either:
```swift
let foo = if condition {
Foo("foo")
} else {
Foo("bar")
}
```
or:
```swift
let foo: Foo = if condition {
.init("foo")
} else {
.init("bar")
}
```
=> [SE-0380] Add `conditionalAssignment` rule, update `redundantType` rule

Sources/FormattingHelpers.swift, Tests/CommandLineTests.swift
This PR fixes [an issue](https://github.com/nicklockwood/SwiftFormat/pull/1361#issuecomment-1445191419) where `redundantReturn` would unexpectedly remove a return for a function nested in a closure.
=> Fix bug in redundantReturn rule

.github/workflows/linux_build.yml
This makes sure `swiftformat` is linked against an old enough version of `glibc` to be able to be used with current stable distributions (like Debian 11, or Ubuntu >= 20.04).
=> Use Ubuntu 20.04 in Linux CI

CHANGELOG.md
Just thought I would help out in bringing SwiftFormat into 2023. :)
Also, I noticed a red bar (how vim shows spelling errors) around "Github" indicating a misspelling, so figured I could correct it to how it is found online and within the site, with the 'h' also capitalised.
=> Update Year and Fix GitHub Spelling.

Sources/Rules.swift, Sources/SwiftFormat.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Syntax.swift
I noticed that [SE-0380](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md) (which added support for if / switch expressions) is now slated for Swift 5.9 instead of Swift 5.8. This PR updates the gating for functionality related to that feature.
=> Update if / switch expression features to be enabled in Swift 5.9+

README.md
For new users installing SwiftFormat, there is a section describing installation options. If you are curious about any particular one, you need to find it manually in the README.
It would be much easier if they linked directly to their relevant sections.
Added links to the relevant sections to make for easier navigation.
=> Link to relevant sections for installation

Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR fixes #1392. In the following example, `opaqueGenericParamaters` was removing the `T` generic parameter because it appeared redundant / unused within the type definition. This behavior would have been correct if the constraint was something like `where T == Int`, but the constraint is actually important here since it's being constrained relative to a  generic type from the parent scope.
```swift
public struct Ref<Value> {}
public extension Ref {
static func weak<Base: AnyObject, T>(
_: Base,
_: ReferenceWritableKeyPath<Base, Value>
) -> Ref<Value> where T? == Value {}
}
```
As a fix we can just avoid removing parameters that seem unused. If the generic type was truly redundant / unused (e.g. with a `T == Int` constraint) the compiler would give us a `generic parameter 'T' is not …
=> Fix issue in #1392 where `opaqueGenericParamaters` would remove non-redundant generic type

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR fixes #1420. We need to preserve `self` in function bodies defined inside closures with a `[weak self]` capture.
=> Fix #1420: preserve self in function bodies inside closures with [weak self] captures

Sources/Tokenizer.swift, Tests/RulesTests+General.swift
This PR fixes the issue #1425 
The `tokenizer` was detecting urls `https://  file:// .. etc.` as `CommentDirective`. This was preventing the header from being removed. After this PR, it will no longer be detected as `CommentDirective` and therefore, the process will continue parsing the header as expected.
=> Fix stripping file header

Sources/Rules.swift, Tests/RulesTests+Linebreaks.swift
- This PR fixes this PR https://github.com/nicklockwood/SwiftFormat/issues/1428
- I updated implementation and test of `blankLineAfterImports`
=> Fix `@_spi` related bug for `blankLineAfterImports` rule

Rules.md, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
Hi, first time contribution here.
This rule removes `Self.` from inside `static func` and `static var`s, since those are redundant, e.g.,
Before
```swift
static func foo() {
Self
.bar()
}
```
After
```swift
static func foo() {
bar()
}
```
Please let me know if something needs to be updated.
=> Redundant static Self

Rules.md, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Organization.swift, Tests/RulesTests+Wrapping.swift
This PR adds a new `sortTypealiases` rule, which nicely compliments the existing `--wraptypealiases` option.
```diff
- typealias Placeholders = Foo & Bar & Baaz & Quux
+ typealias Placeholders = Baaz & Bar & Foo & Quux
typealias Dependencies
-     = FooProviding
+     = BaazProviding
& BarProviding
-     & BaazProviding
+     & FooProviding
& QuuxProviding
```
=> Add `sortTypealiases` rule

Sources/SwiftFormat.swift
Reuse the implementation of `NSString`'s `isAbsolutePath` to determine if the path is absolute rather than re-implementing that logic inline. This allows use of `SwiftFormat` with the vknabel/SwiftFormat extension with Visual Studio Code on Windows.
We would previously attempt to check if the configuration path was absolute by checking for a leading `/` which does not represent an absolute path on Windows but rather a relative path (it is drive relative).  We perform a bit more bridging here but get the portable behaviour without resorting to manually invoking `IsPathRelativeW` on the path representation.  This also allows us to pick up the improvements to the path handling in Foundation for long paths without having to reconstruct special handling.
=> SwiftFormat: adjust `expandPath` to be more portable

.github/workflows/build.yml
Add the GHA workflow rules to enable the CI to also include Windows to prevent accidental regressions.  Since both macOS and Linux builds include the code coverage reporting, add that to Windows as well.
=> GHA: add Windows CI integration and Code Coverage reporting

.github/workflows/windows_release.yml, Platforms/Windows/SwiftFormat.wixproj, Platforms/Windows/SwiftFormat.wxs, Platforms/Windows/WixCodeSigning.targets
Add some build rules to package up a Windows installer for release builds.  Perform a separate build that is a release configuration and does not include debug information to minimise size and optimize load times.
Package this up into a MSI installer.  Ideally, we would perform code signing for the MSI and the binary, but that can be done as a follow up as it requires a Code Signing certificate to be available.
The default install location is:
`%SystemDrive%\Program Files\nicklockwood\SwiftFormat`
following Windows conventions of
`[ProgramFiles][Manufacturer][ProductName]`.
Prefer to use `swoftprops/action-gh-release` over `actions/release` as the latter is marked as deprecated.
=> GHA: add a workflow for performing a Windows release

Platforms/Windows/SwiftFormat.wixproj, Platforms/Windows/SwiftFormat.wxs
Correct the closing tag from `Directory` to match the opening tag of `StandardDirectory`.
=> Windows: correct the XML tag for the installer manifest

.github/workflows/windows_release.yml
Use a non-pre-release release tag and include the Swift version information into the tag to permit parallel releases of the same version until we can page the runtime into the distribution.
=> GHA: adjust release tagging for Windows

Rules.md, Snapshots/Euclid/Sources/Paths.swift, Snapshots/Euclid/Sources/Plane.swift, Snapshots/Euclid/Sources/Polygon.swift, Snapshots/Euclid/Sources/Transforms.swift, Snapshots/Euclid/Sources/Vector.swift, Snapshots/Euclid/Sources/Vertex.swift, Snapshots/Issues/794.swift, Snapshots/Layout/Layout/LayoutError.swift, Snapshots/Layout/Layout/LayoutNode.swift, Snapshots/Layout/Layout/RuntimeType.swift, Snapshots/Layout/Layout/UIView+Layout.swift, Sources/Examples.swift, Sources/Rules.swift, Tests/RulesTests+Organization.swift, Tests/RulesTests+Redundancy.swift
This PR adds a new `redundantInternal` rule, which removes the `internal` keyword from declarations when it's redundant and doesn't affect the declaration's access control level:
```diff
- internal class Foo {
+ class Foo {
-     internal let bar: String
+     let bar: String
-     internal func baaz() {}
+     func baaz() {}
-     internal init() {
+     init() {
bar = "bar"
}
}
```
This excludes declarations in non-internal extensions:
```swift
public extension Foo {
/// `internal` is not redundant here since the extension is public, 
/// and removing `internal` would make the declaration public
internal func bar() {}
}
```
=> Add `redundantInternal` rule

Sources/Rules.swift, Tests/RulesTests+Linebreaks.swift
`blankLinesAtStartOfScope`, `blankLinesAtEndOfScope` are here to add blank lines (not delete them).
`blankLinesBetweenImports` & `consecutiveBlankLines` can delete blankLines but are designed to keep one blank line.
If a developer introduces blankLines between chained funcs during development I haven't found a rule to guarantee deletion of these lines.
I propose to introduce a new `blankLinesBetweenChainedFuncs` rule that for this kind of code
```swift
[0, 1, 2]
.map { $0 * 2 }
.map { $0 * 3 }
```
will produce
```swift
[0, 1, 2]
.map { $0 * 2 }
.map { $0 * 3 }
```
P.S: If this is achievable with the current existing rules and result from a misunderstanding on my end, then this PR can be closed. And will be curious about to achieve it :)
=> New rule: "blankLinesBetweenChainedFuncs"

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR fixes several edge cases in the `forLoop` rule that I missed in #1490.
This PR also adds options to:
1. not convert anonymous `forEach` closures to `for` loops
2. convert single-line `forEach` closures to multi-line `for` loops
=> Fix edge cases in `forLoop` rule

README.md, Sources/CommandLine.swift, Sources/FormattingHelpers.swift, Sources/GitHelpers.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Sources/ShellHelpers.swift, Sources/SwiftFormat.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/ArgumentsTests.swift, Tests/RulesTests+General.swift, Tests/SwiftFormatTests.swift
Hi! Thank you for this tool, it helps tremendously when working on Swift projects 🙏 
When setting up a configuration for a project where I want to generate the header I noticed that the "Created by" row is hard to keep as generated by Xcode, so I thought `{created.name}` and `{created.email}` could be a nice addition to the templating 🙂
The PR reworks the templating a bit to make it more loop-based, which could make it easier to add more placeholders later if needed.
It also fixes a bug where each placeholder could only be used once.
Related issue: #776
=> Add file header placeholders for user who created the file

Rules.md, Sources/Examples.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+General.swift, Tests/RulesTests+Organization.swift, Tests/RulesTests+Redundancy.swift
This PR adds a new disabled-by-default `noExplicitOwnership` rule, which removes `borrowing` and `consuming` ownership modifiers.
Ownership modifiers do not affect the correctness of code, and adding / removing them does not affect behavior. Some teams may prefer to avoid using these modifiers (except in truly performance-critical code) since they would add mental overhead for little gain in most cases.
```diff
- borrowing func foo(_ bar: consuming Bar) { ... }
+ func foo(_ bar: Bar) { ... }
```
=> Add `noExplicitOwnersip` rule

Sources/Rules.swift, Tests/RulesTests+Organization.swift
With the `sortTypealiases` rule we've found its pretty common for folks to unintentionally add a type to the protocol composition multiple times. This can be hard to notice when the typealias isn't sorted, especially if the typealias is quite long:
```swift 
typealias Dependencies
= FooProviding
& BarProviding
& BaazProviding
& QuuxProviding
& FooProviding
```
but is quite obvious after its sorted:
```swift
typealias Dependencies
= BaazProviding
& BarProviding
& FooProviding
& FooProviding
& QuuxProviding
```
Since we're already parsing and reordering these in the `sortTypealiases` rule, we may as well also remove duplicates:
```swift
typealias Dependencies
= BaazProviding
& BarProviding
& FooProviding
& QuuxProviding
```
=> Update sortTypealiases rule to also remove duplicates

README.md
I built an extension for Panic's Nova code editor, so I was hoping to add a link from the Readme here.
=> Add link to Nova extension

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR fixes #1525, where the redundant return rule would unexpectedly remove the `return` keyword from a conditional statement in a failable init, where explicit return is required.
```diff
init?(optionalHex: String?) {
if let optionalHex {
self.init(hex: optionalHex)
} else {
-        return nil
+        nil
}
}
```
```diff
init?(optionalHex: String?) {
if let optionalHex {
self.init(hex: optionalHex)
} else {
return nil
}
}
```
=> [#1525] Fix issue where removing return from failable init would break build

Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Syntax.swift
This PR improve `conditionalAssignment` and `redundantClosure` rules by updating them to parse full expressions, rather than using a set of loose heuristics.
This PR adds a `parseExpressionRange` helper, which parses [all of the expression types](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/expressions/) in the Swift grammar. Then we can simplify `blockBodyHasSingleStatement` to just to parse the expression in the body to verify that the entire body is a single expression.
Fixes #1538.
=> Improve `conditionalAssignment` and `redundantClosure` rules by parsing full expressions

Sources/FormattingHelpers.swift, Sources/Inference.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Tests/RulesTests+Wrapping.swift
Thank you for taking the time to review this PR. I believe this new feature will be a valuable addition to the project and benefit many users. I'm open to feedback and suggestions, and I'm more than happy to make any necessary changes to ensure that this fits perfectly within the project's guidelines and objectives.
**In Summary:**
- **Idea Behind the Changes:** This PR introduces a more refined approach to handling the positioning of closing parentheses, specifically distinguishing between _function-calls_ and _function-declarations_. The aim is to enable more granular control over formatting, while ensuring existing configurations remain unaffected.
- **Refinement to Existing `closingParenOnSameLine` Option:** While the `closingParenOnSameLine` option already existed, providing control …
=> Function definition vs calls, support `closingparen` in raywenderlich style guide

Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Redundancy.swift
This PR updates the `redundantClosure` rule to preserve closures with if/switch expressions if the closure is in a position where an if/switch expression would not be allowed. In Swift 5.9 if/switch expressions are only allowed as either return values, or as the result of an assignment.
This PR also fixes miscellaneous issues where `redundantClosure` didn't properly handle some combinations of explicit `return`, `try`/`await`, and if/switch expressions.
Fixes #1547 and #1548.
=> Update `redundantClosure` rule to preserve closure where if/switch expression would not be allowed

Sources/FormattingHelpers.swift, Sources/Rules.swift, Sources/SwiftFormat.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Syntax.swift
This PR fixes two issues where SwiftFormat would convert code to use if/switch expressions that did not compile:
1. If / switch expressions are not permitted in method calls, like:
```swift
XCTAssert(if condition {
foo
} else {
bar
}
```
2. Due to [this issue](https://github.com/apple/swift/issues/68764) in Swift 5.9 (fixed in 5.10), `as?` operators are not supported in if/switch expressions. This example does not compile in Swift 5.9:
```swift
let result: String? = if condition {
foo as? String
} else {
"bar"
}
```
=> Fix more edge cases related to if/switch expressions

Snapshots/Layout/Layout/ReloadManager.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR fixes an issue where the `enumNamespaces` rule wouldn't be applied to a type following an import statement. Fixes #1569.
=> Fix issue where `enumNamespaces` rule wouldn't be applied following import statement

Sources/Tokenizer.swift, Tests/RulesTests+Redundancy.swift, Tests/TokenizerTests.swift
This PR fixes an issue where switch cases with multiple where clauses could parse incorrectly. Fixes https://github.com/nicklockwood/SwiftFormat/issues/1554.
Specifically, the `<` token in the example below was unexpectedly being tokenized as a `.startOfScope` token, leaving the `:` tokenized as a `delimiter` instead of a `startOfScope`. This broke the logic in `switchStatementBranches`, which was looking for a `.startOfScope(":")`.
```swift
func foo(cases: FooCases, count: Int) -> String? {
switch cases {
case .fooCase1 where count == 0:
return "foo"
case .fooCase2 where count < 100,
.fooCase3 where count < 100,
.fooCase4:
return "bar"
default:
return nil
}
}
```
=> Fix issue where switch case with multiple where clauses could parse incorrectly

Sources/FormattingHelpers.swift, Tests/RulesTests+Redundancy.swift
This PR fixes an issue where `conditionalBranchHasUnsupportedCastOperator` handled `as?` casts but not `as!` casts (which are also unsupported in if/switch expressions in Swift 5.9).
=> Update if/switch expression workaround for Swift 5.9 bug to handle `as!` cast

Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Tests/RulesTests+Syntax.swift
This PR fixes an issue where a `for` loop a conditional branch would break the `conditionalAssignment` rule. This is because we were unexpectedly treating the `in` keyword in the for loop as the `in` keyword following a closure capture list.
=> Fix issue where for loop would break `conditionalAssignment` rule

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Wrapping.swift
This PR updates the `wrapAttributes` rules to support being applied differently to computed properties vs stored properties.
Take this example SwiftUI view:
```swift
struct MyView: View {
@State var textContent: String
var body: some View {
childView
}
@ViewBuilder
var childView: some View {
Text(verbatim: textContent)
}
}
```
We want the `@ViewBuilder` attribute to be on its own line, but the `@State` attribute to be on the same line as the property declaration. Previously this wasn't possible. Now this is supported using `--computedvarattrs prev-line --storedvarattrs same-line`.
---
Separately, when looking at adopting `--varattributes prev-line`, I noticed a type of case where I think we should preserve the existing formatting instead of wrapping. Take this example, with a max line …
=> Support configuring `wrapAttributes` rule to apply differently to computed properties vs stored properties

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/OptionDescriptorTests.swift, Tests/RulesTests+Wrapping.swift
This PR adds a `--complexattrs` option to support wrapping complex attributes (attributes with arguments) differently from simple attributes (without arguments).
We want to use `--storedvarattrs same-line` for common attributes like `@State` and `@objc`:
```swift
@State private var foo: Foo
@objc private var bar: Bar
``` 
but the most idomatic usage of longer attributes (typically those with arguments, like `@available` or custom DSLs like Swift argument parser) is to leave them on the previous line:
```swift
// Uncommon:
@available(*, deprecated, message: "Deprecated!") var foo: WrappedType
@Option(help: "The absolute path to the SwiftFormat config file") var swiftFormatConfig: String
// More common:
@available(*, deprecated, message: "Deprecated!") 
var foo: WrappedType
@Option(help: …
```
=> Add option to wrap complex attributes with arguments differently than simple attributes without arguments

Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Wrapping.swift
This PR updates the `wrapAttributes` "complex attributes" logic to exclude attributes with a single unnamed argument.
This removes the need to special-case the `@Environment` attribute, which we specifically don't want to consider "complex". Since this doesn't require special casing any particular attribute, it generalizes to other similar attributes like `@AppStorage` from SwiftUI and `@Dependency` from TCA.
These are no longer considered complex, so can be configured to not wrap using `--storedvarattrs same-line`:
```swift
@Environment(\.controlPanelStyle) private var controlPanelStyle
@Dependency(\.controlsService) private var controlsService
@AppStorage("ControlsConfig") private var controlsConfig: ControlConfiguration
```
These examples are all still considered complex, so can be …
=> Update wrapAttributes "complex attributes" logic to exclude attributes with a single unnamed argument

Sources/ParsingHelpers.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Wrapping.swift
This PR fixes an issue where the `parseType` helper didn't handle qualified types like `Foo.Bar` or `Foo.Bar.Baaz`. 
This could cause the `isStoredProperty(atIntroducerIndex:)` helper to return the incorrect result for properties with a qualified type name, like in the example added as a test case.
=> Fix issue where parseType helper didn't handle qualified types like Foo.Bar

.github/workflows/linux_build.yml
Currently, the pre-built binary targeting Linux links Swift stdlib and core libraries dynamically. Unlike darwin platforms, Swift does not guarantee ABI stability on Linux, so the pre-built binary must be run with exactly the same version of Swift stdlib and core libraries that it was built with on GitHub Actions. And also the shared libraries can be installed in various locations, so users usually need to set `LD_LIBRARY_PATH`.
However, asking users to do the above works only for power users. Reducing the runtime dependencies makes it usable for more users.
The only downside of static-linkage is the significant binary-size (9.4M -> 57M). But IMHO a larger binary is better than the one hard to run. The most of huge binary size came from unused ICU data and Foundation, so we can expect it …
=> Remove runtime stdlib dependency from pre-built binary targeting Linux

Rules.md, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Indentation.swift, Tests/RulesTests+Organization.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Spacing.swift, Tests/RulesTests+Syntax.swift
This PR adds two new rules related to blank lines in switch statements. 
This rule inserts a blank line following any switch statement case that spans multiple lines:
```diff
func handle(_ action: SpaceshipAction) {
switch action {
case .engageWarpDrive:
navigationComputer.destination = targetedDestination
await warpDrive.spinUp()
warpDrive.activate()
+
case let .scanPlanet(planet):
scanner.target = planet
scanner.scanAtmosphere()
scanner.scanBiosphere()
scanner.scanForArticialLife()
+
case .handleIncomingEnergyBlast:
await energyShields.prepare()
energyShields.engage()
}
}
```
This rule ensures that the cases in a switch statement have consistent spacing. If the majority of cases have a blank line, then all cases should have a blank line. This is complimentary with the above rule, and …
=> Add new rules related to blank lines in switch statements

Sources/FormattingHelpers.swift, Sources/Tokenizer.swift, Tests/RulesTests+Syntax.swift
This PR fixes some bugs in how the `conditionalAssignment` rule handled `@unknown default` cases, which could result in build failures. For example:
```swift
let foo: Foo
switch condition {
case .foo:
foo = Foo("foo")
case .bar:
foo = Foo("bar")
@unknown default:
foo = Foo("default")
}
```
was being converted to:
```swift
let foo = switch condition {
case .foo:
Foo("foo")
case .bar:
Foo("bar")
@unknown default:
foo = Foo("default")
}
```
=> Fix conditionalAssignment bugs with @unknown default cases

Sources/Rules.swift, Tests/RulesTests+Organization.swift
This PR fixes an issue where declaration bodies wouldn't be sorted if the `organizeDeclarations` rule was enabled, but configured with a `organizeTypes` value that excluded that declaration type.
For example, `organizeTypes` excludes extensions by default. So when `organizeDeclarations` was enabled, the neither the `sortDeclarations` rule nor the `organizeDeclarations` rule would apply the `// swiftformat:sort` directive.
This PR should fix https://github.com/nicklockwood/SwiftFormat/issues/1622.
=> Fix issue where declaration body wouldn't be sorted if organizeDeclarations was enabled but excluded declaration type

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR makes two improvements to the `docComments` rule.
First, this PR adds a `--doccomments preserve` options. When this option is enabled, it disables the part of the rule that converts doc comments into regular comments, so the rule will only ever convert regular comments into doc comments.
Second, this PR updates the rule to preserve any regular comments preceding a block of grouped declarations. For example:
```swift
/// The planets of the solar system
enum Planets {
// Inner planets
case mercury
case venus
case earth
case mars
// Inner planets
case jupiter
case saturn
case uranus
case neptune
// Dwarf planets
case pluto
case ceres
}
```
Since the comments refer to the code block as a whole, and not a specific property, it makes sense to use regular comments rather than doc …
=> Add option to preserve all doc comments, preserve regular comments before grouped declarations

Sources/SwiftFormat.swift
Now that we know that the next version of Swift will be Swift 6.0 ([link](https://forums.swift.org/t/swift-6-0-release-process/70220)), it seems like it makes sense to go ahead and add support for `--swift-version 6.0` by adding it as a supported version.
=> Add Swift 6.0 to list of supported Swift versions

Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Syntax.swift, Tests/RulesTests+Wrapping.swift
This PR updates the `conditionalAssignment` rule to also simplify if/switch expressions that don't immediately follow property declarations.
Previously the `conditionalAssignment` rule only handled if/switch expressions that followed a property declaration:
```swift
// Before
let property: Foo
if condition {
property = Foo("foo")
} else {
property = Foo("bar")
}
// After
let property =
if condition {
Foo("foo")
} else {
Foo("bar")
}
```
but did nothing in other cases like this:
```swift
if condition {
property = Foo("foo")
} else {
property = Foo("bar")
}
```
Now we apply the simplification to this case as well:
```swift
// Before
if condition {
property = Foo("foo")
} else {
property = Foo("bar")
}
// After
property =
if condition {
Foo("foo")
} else {
Foo("bar")
}
```
=> Update conditionalAssignment rule to also simplify if/switch expressions that don't immediately follow property declaration

Rules.md, Sources/Examples.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Syntax.swift, Tests/RulesTests+Wrapping.swift
This PR adds a new `preferInferredTypes` rule that converts property declarations with an explicit type (e.g. `let foo: Foo = .init()`) to instead use an inferred type (`let foo = Foo()`).
```diff
- let foo: Foo = .init()
+ let foo = Foo()
- let bar: Bar = .defaultValue
+ let bar = Bar.defaultValue
- let baaz: Baaz = .buildBaaz(foo: foo, bar: bar)
+ let baaz = Baaz.buildBaaz(foo: foo, bar: bar)
let float: CGFloat = 10.0
let array: [String] = []
let anyFoo: AnyFoo = foo
```
Another approach I considered, but didn't implement, was to have a more general `propertyDeclarationTypes` rule that can also do the inverse transformation (convert `let foo = Foo()` to `let foo: Foo = .init()`). 
That conversion is more error-prone, since we don't exactly know what the name of the type is. For example, …
=> Add preferInferredTypes rule

Rules.md, Sources/Examples.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift, Tests/RulesTests+Wrapping.swift
This PR updates the `conditionalAssignment` rule to support more complex lvalues. Previously it required that the value being assigned was just a simple identifier like `foo =`. Now it supports more complex lvalues like `foo?.bar =`, `foo["bar"] =`, etc.
For example, this sample code was left as-is before:
```swift
switch condition {
case true:
property?.foo!.bar["baaz"] = Foo("foo")
case false:
property?.foo!.bar["baaz"] = Foo("bar")
}
```
Now it is updated as expected:
```swift
property?.foo!.bar["baaz"] =
switch condition {
case true:
Foo("foo")
case false:
Foo("bar")
}
```
I also added a new `--condassignment after-property` to let consumers disable the new functionality added in https://github.com/nicklockwood/SwiftFormat/pull/1643. After running the updated rule on our codebase, I …
=> Update conditionalAssignment rule to support more complex lvalues

Rules.md, Sources/Examples.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
The PR extends the `preferInferredTypes` rule to support if/switch expressions.
Previously this example was left as-is:
```swift
let foo: Foo =
if condition {
.init(bar)
} else {
.init(baaz)
}
```
Now it's converted to:
```swift
let foo =
if condition {
Foo(bar)
} else {
Foo(baaz)
}
```
=> Extend preferInferredTypes rule to support if/switch expressions

Rules.md, Sources/Examples.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Indentation.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests+Syntax.swift
This PR adds a new `redundantProperty` rule, which removes a property declaration if that property is just returned immediately. For example:
```diff
func foo() -> Foo {
-   let foo = Foo()
-   return foo
+   return Foo()
}
```
Here's an example of a pattern I saw somewhat frequently in Airbnb's codebase:
```swift
func foo() -> Foo {
let foo: Foo
switch condition {
case true:
foo = Foo(bar)
case false:
foo = Foo(baaz)
}
return foo
}
```
The `conditionalAssignment` rule converts this to `let foo = switch { ... }; return foo`. Now with both `conditionalAssignment` and `redundantProperty` enabled, it's instead converted to an even simpler form:
```swift
func foo() -> Foo {
switch condition {
case true:
Foo(bar)
case false:
Foo(baaz)
}
}
```
=> Add redundantProperty rule

Sources/FormattingHelpers.swift, Tests/RulesTests+Wrapping.swift
This PR fixes an issue where the `--wrapreturntype if-multiline` option didn't work if the return type was an array, dictionary, tuple, or generic type.
=> Fix issue where --wrapreturntype if-multiline didn't work with arrays, dictionaries, tuples, or generic types

README.md, Sources/Arguments.swift, Sources/CommandLine.swift
This PR adds a new `--strict` option that causes SwiftFormat to emit a non-zero exit code if it applies any formatting changes.
Within Airbnb we want our tooling to be able to detect when running SwiftFormat applies formatting changes. Historically we've done this by running SwiftFormat twice: once with `--lint` to determine whether or not there are changes needing formatting, and then again without `--lint`. This isn't very efficient since it requires running SwiftFormat twice, so instead we'd like to just run SwiftFormat a single time. A `--strict` option is really helpful for this.
As an example of prior art, [SwiftLint](https://github.com/realm/SwiftLint) also provides a `--strict` flag with this exact same functionality (it causes autocorrect to return a non-zero exit code after …
=> Add --strict option to emit non-zero exit code after applying changes

Sources/ParsingHelpers.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Redundancy.swift
This PR fixes a bug in the `redundantInit` rule for `.init` calls in ternary operators. It was unexpectedly converting code like:
```swift
let bar: Bar = (foo.isBar && bar.isBaaz) ? .init() : nil
```
to
```swift
let bar: Bar = (foo.isBar && bar.isBaaz) ? () : nil
```
=> Fix redundantInit bug in ternary operators

Rules.md, Sources/Examples.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
Related https://github.com/nicklockwood/SwiftFormat/issues/1677 .
Added `—nilinit` option to `redundantNilInit` rule, its value includes `insert` and `remove`. Among them, `remove` is consistent with the previous logic, and `insert` is a new logic. It will add `nil` as the default value after the optional value type according to the opposite rules of `remove`.
> I did not implement the `properties-only` option mentioned in the issue, firstly because I did not need it, and secondly because I was not familiar enough with this project.
I added documentation and test cases and all of them passed.
This is my first PR for this project. If I did something wrong or if there is anything else that needs to be modified, please let me know.
=> Add `—nilinit` for `redundantNilInit` rule

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR fixes a bug in the `unusedArguments` rule when shadowing a function argument with a declaration where the value is an if or switch expression. 
```swift
func test(foo _: Foo) {
let foo =
if foo.bar {
baaz
} else {
bar
}
print(foo)
}
```
```swift
func test(foo: Foo) {
let foo =
if foo.bar {
baaz
} else {
bar
}
print(foo)
}
```
=> Fix bug in `unusedArguments` when shadowing function argument with conditional assignment declaration

Sources/Rules.swift, Tests/RulesTests+Spacing.swift
SE-0430 has been [accepted](https://forums.swift.org/t/accepted-with-modifications-se-0430-second-review-sendable-parameter-and-result-values/71850) which adds the `sending` keyword.
This PR adds support for the keyword to the spaceAroundParens & spaceAroundBrackets rules.
=> Support SE-0430 `sending` in spaceAroundBrackets/Parens

Sources/Tokenizer.swift, Tests/RulesTests+Spacing.swift, Tests/TokenizerTests.swift
`~` is used in generic scopes to [suppress conformances (SE-0427)](https://github.com/apple/swift-evolution/blob/main/proposals/0427-noncopyable-generics.md).
```swift
func foo<T: ~Copyable>() {}
```
This ensures generic scopes containing `~` are parsed as generic scopes, otherwise the `<` and `>`are interpreted as operators.
I added a basic tokenizer test and some tests for the `spaceAroundOperators` rule for cases that incorrectly add space around `<` and `>` without this change. Feel free to let me know if there are other tests I should add as well.
It probably makes sense to hold off on merging this until SE-0427 has been accepted.
=> Add "~" to the allowed operators in generic scopes

Rules.md, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/MetadataTests.swift, Tests/RulesTests+Organization.swift
This one will be a longshot 🙃
This PR adds an ability to organize types by `type` rather than `visibility` (but its more like an attempt to make this rule a bit more extensible). Within our project somewhat similar fork lives for around a year atm.
Have no idea of what direction this PR should take, so any comments and suggestions are highly appreciated 🥹
=> `organizeDeclarations` by type

Sources/ParsingHelpers.swift, Tests/RulesTests+Syntax.swift
This PR fixes #1709.
This code was being parsed incorrectly:
```swift
dict.forEach { (header: (key: String, value: String)) in
print(header.key)
print(header.value)
}
```
so was unexpectedly converted to:
```swift
for (header, value) in dict {
print(header.key)
print(header.value)
}
```
instead of:
```swift
for header in dict {
print(header.key)
print(header.value)
}
```
=> Fix closure argument list parsing bug in preferForLoop rule

Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR improves attribute handling in the `opaqueGenericParameters` rule.
To fix #1684, https://github.com/nicklockwood/SwiftFormat/commit/383fd4813c7fb45e4e996242b6c7c919133f5dc1 made it so the `opaqueGenericParameters` was disabled for all functions with attributes. However, in most cases attributes don't cause any issues. For example:
```swift
@MyResultBuilder
func foo<T: Foo, U: Bar>(foo: T, bar: U) -> MyResult {
foo
bar
}
@MyFunctionBodyMacro(withArgument: true)
func foo<T: Foo, U: Bar>(foo: T, bar: U) {
print(foo, bar)
}
```
This PR tweaks the existing fix to check the tokens of the attributes, and whether or not they reference any of the generic arguments. #1684 remains fixed, and the above examples are now updated as expected:
```swift
@MyResultBuilder
func foo(foo: some Foo, …
```
=> Improve attribute handling in opaqueGenericParameters rule

Sources/FormattingHelpers.swift, Tests/RulesTests+Organization.swift
This PR fixes a regression introduced by #1678 where conditional compilation blocks would be sorted incorrectly (always at the bottom).
Previously the `organizeDeclarations` rule supported a partial ordering, where any declaration without a defined type would just preserve its existing relative ordering. The architecture changes to the `organizeDeclaration` rule now require a total ordering of declarations, so every declaration must have a well defined type.
Since conditional compilation blocks can have multiple nested declarations with different types, we previously just used `type: nil` for these. #1678 made these a type of their own which was sorted last. Now, we instead use the type of the first declaration in the conditional compilation block. This better matches the previous …
=> Fix issue where conditional compilation blocks would be sorted incorrectly

Sources/ParsingHelpers.swift, Tests/ParsingHelpersTests.swift, Tests/RulesTests+Redundancy.swift
This PR fixes a bug where the body of an if statement could be incorrectly parsed as a trailing closure.
This fixes an issue where the `redundantProperty` rule would incorrectly convert this code:
```swift
func foo() -> Foo {
let foo = Foo(bar: bar, baaz: baaz)
if let foo = foo.nestedFoo {
print(foo)
}
return foo
}
```
to:
```swift
func foo() -> Foo {
let foo = Foo(bar: bar, baaz: baaz)
if return foo.nestedFoo {
print(foo)
}
}
```
=> Fix bug where if statement body could be incorrectly parsed as trailing closure

Rules.md, Sources/Examples.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR adds a new `redundantTypedThrows` rule, which removes a typed throws (introduced in Swift 6.0) if it is redundant. 
For example:
```diff
- func foo() throws(Never) -> Int {
+ func foo() -> Int {
return 0
}
- func foo() throws(any Error) -> Int {
+ func foo() throws -> Int {
throw MyError.foo
}
```
We don't remove `(Error)` because we can't guarantee it will reference the `Swift.Error` protocol
(it's relatively common to define a custom error like `enum Error: Swift.Error { ... }`).
=> Add redundant typed throws rule

Sources/Rules.swift, Tests/RulesTests+Linebreaks.swift
Updating the `blankLinesBetweenChainedFunctions` rule to take comments into account when removing blank lines between chained functions.
So this:
```swift
[0, 1, 2]
.map { $0 * 2 }
// Multiplies by 3
.map { $0 * 3 }
```
Will turn into:
```swift
[0, 1, 2]
.map { $0 * 2 }
// Multiplies by 3
.map { $0 * 3 }
```
cc @calda
=> Support comments when removing spaces between chained functions

.github/workflows/release.yml, Scripts/spm-artifact-bundle.sh
This PR adds a GitHub Actions CI job that builds `swiftformat.artifactbundle.zip` for each new release and automatically uploads / attached it to the release page.
- Here's an example release using this: https://github.com/calda/SwiftFormat/releases/tag/0.54-test-upload-release-artifact-3
- And here's the action run that buildtand uploaded the `swiftformat.artifactbundle.zip` file to that release: https://github.com/calda/SwiftFormat/actions/runs/9454508406
I cut new releases regularly over in https://github.com/calda/SwiftFormat/releases, so automating this process would be helpful. To use this job in that repo I have to upstream it here. I don't know how you're managing this today, but hopefully automating this is helpful for you as well!
I verified that the artifact bundle can be …
=> Add CI job to build and upload artifact bundle for releases

.github/workflows/release.yml
The release new action from #1721 didn't trigger properly for 0.54.0. 
Right now the job uses a `release: [created]` trigger. The [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) says:
> Note: Workflows are not triggered for the `created`, `edited`, or `deleted` activity types for draft releases. When you create your release through the GitHub browser UI, your release may automatically be saved as a draft.
This is probably the most likely explanation for why it didn't work.
It sounds like the recommended trigger is `published` rather than `created`:
```
on:
release:
types: [published]
```
so this PR updates the trigger. Hopefully now it'll work for 0.54.1!
=> Update trigger for release action from `created` to `published`

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR mainly fixes the following issues:
- Fixed the issue that the newly added `--nilInit insert` option for `redundantNilInit` in 0.54.0 was incorrectly applied to computed properties.
Also I fixed some test case errors related to `--nilInit insert`.
=> Fix `--nilInit insert` being applied to computed property

Rules.md, Sources/Examples.swift
Related: https://github.com/nicklockwood/SwiftFormat/issues/849
Added an example syntax for the `modifiersOrder` option and separate section about default order by groups in the Rules.md doc.
=> `modifierOrder` option documentation clarification

Rules.md
The missing diff statments caused consecutiveBlankLines to be hidden in the conditionalArgument's example
=> Fixed formatting for conditionalArgument on Rules.md

Sources/CommandLine.swift
closes #1741
This PR improves support for running `--lint` when providing input from stdin. The reporter.write is now invoked similarly to how it is when the file is read directly from disk.
There is still one issue I've not figured out. The `indent` rule is flagged for every single line of the input when supplied via stdin. Must be something to do with how it is read/how the rule detects newlines/indentation.
However, I think that could warrant its own issue and PR if this one is accepted.
As an aside, I don't use xcode, just the swift cli and swift package manager, so not sure if anything else is required for this change.
=> Fixes linting with stdin

Sources/FormattingHelpers.swift, Tests/RulesTests+Organization.swift
Add a new SwiftUI Property wrapper declaration type to allow sorting instance properties based on this new declaration type. For Example
```diff
struct ContentView: View {
-    let foo: Foo
@State let isOn: Bool
+    @State let quux: Quux
+    let foo: Foo
let baaz: Baaz
-    @State let quux: Quux
@ViewBuilder
private var toggle: some View {
Toggle(label, isOn: $isOn)
}
@ViewBuilder
var body: some View {
toggle
}
}
```
=> Add SwiftUI Property Wrapper declaration type

Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/ParsingHelpersTests.swift
This PR adds a new `originalRange` property to the `Declaration` type.
This makes it easier to use `parseDeclarations()` to implement new rules, since now you know where the individual declarations actually are in the source file. @mannylopez will use this functionality in a new rule he's working on.
=> Include original token range when parsing declarations

Rules.md, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift, Tests/RulesTests.swift
Rule to remove unused `private` and `fileprivate` declarations
```diff
struct Foo {
--    fileprivate var foo = "foo"
--    fileprivate var baz = "baz"
var bar = "bar"
}
struct Foo {
var bar = "bar"
--
--    fileprivate func sayHi() {
--        print("hi")
--    }
}
```
@calda
=> Add unusedPrivateDeclaration rule to remove unused private and fileprivate declarations

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
@calda pointed out that it's safer to remove unused private `let`, `var`, and `func` declarations lest we remove something that is indeed being used.
To ensure this, I'm adding `let allowList = ["let", "var", "func"]` and `guard allowList.contains(kind) else { break }` to rule `unusedPrivateDeclaration`.
---
For reference, this is what we are using as declarations:
```swift
// ParsingHelpers.swift
...
static var declarationTypeKeywords: Set<String> {
swiftTypeKeywords.union([
"import", "let", "var", "typealias", "func", "enum", "case",
"struct", "class", "actor", "protocol", "init", "deinit",
"extension", "subscript", "operator", "precedencegroup",
"associatedtype", "macro",
])
}
```
=> Add allowList to unusedPrivateDeclaration

Rules.md, Sources/Examples.swift, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Tests/OptionDescriptorTests.swift, Tests/RulesTests+Organization.swift
This PR improves the expressiveness of the `organizeDeclaration` rule's `--typeorder` and `--visibilityorder` options.
The `--typeorder` and `--visibilityorder` arguments that best correspond to the behavior [defined](https://github.com/airbnb/swift#subsection-organization) in Airbnb's style guide would be:
```
--visibilityorder beforeMarks,instanceLifecycle,open,public,package,internal,private,fileprivate
--typeorder nestedType,staticProperty,staticPropertyWithBody,classPropertyWithBody,instanceProperty,instancePropertyWithBody,staticMethod,classMethod,instanceMethod
```
However this is not currently allowed, because `--typeorder` is currently required to contain `beforeMarks` and `instanceLifecycle`. Additionally, `beforeMarks` and `instanceLifecycle` are hardcoded to always be enabled …
=> Improve expressiveness of --typeorder and --visibilityorder options

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
See the newly added unit tests for details.
As of version 0.54.1, `--nilInit insert` will incorrectly make the following changes:
```diff
- var jsonObject = json as? [String: Int]
+ var jsonObject = json as? = nil [String: Int] // ❌ Wrong, should not be replaced
```
This PR fixes this issue
=> Fix `--nilInit insert` being applied to `as` keyword

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
=> Fix issue where redundantInternal would unexpectedly remove internal access control from declaration in public extension with where clause

Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
After talking to @mannylopez about https://github.com/nicklockwood/SwiftFormat/pull/1761 we realized that `typealias` could also go in the `unusedPrivateDeclaration` allowlist. 
I also wanted to double-check that `// swiftformat:disable:next unusedPrivateDeclaration` worked as expected, so I added a test case for that.
=> Add typealias to unusedPrivateDeclaration allowlist

Rules.md, Sources/Examples.swift, Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR adds a new `docCommentBeforeAttributes` rule that ensures any doc comments on a declaration come before, not after, the declaration's attributes. For example:
```diff
+ /// Doc comment on this function declaration
@MainActor
- /// Doc comment on this function declaration
func foo() {}
```
=> Add docCommentBeforeAttributes rule

Rules.md, Sources/Examples.swift, Sources/Rules.swift, Tests/RulesTests+Organization.swift, Tests/RulesTests+Syntax.swift
This PR makes a few follow-up improvements to the new `docCommentsBeforeAttributes` rule, including fixing an issue where the rule wasn't applied following `// MARK:` or `// TODO` comments.
=> Improve docCommentsBeforeAttributes rule, fix support for declarations after MARK comments

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
This PR will fix some false-positives found when using the `unusedPrivateDeclaration` rule.
1. 
```swift
struct ContentView: View {
public init() {
_showButton = .init(initialValue: false)
}
@State private var showButton: Bool
}
```
2. 
```swift
// Declaration
extension CGSize {
fileprivate static var `default`: CGSize { .init(width: 10, height: 10) }
}
// Usage
let defaultSize = CGSize.default
```
3.
=> Update unusedPrivateDeclaration and handle false positives

Sources/ParsingHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Syntax.swift
This PR updates the `docCommentsBeforeAttributes` rule to only apply to doc comments. Previously it also applied to regular comments, which is unexpected given the name of the rule. https://github.com/nicklockwood/SwiftFormat/pull/1770#discussion_r1687510809
=> Update docCommentsBeforeAttributes rule to only apply to doc comments

Sources/FormattingHelpers.swift, Tests/RulesTests+Wrapping.swift
This PR fixes an issue where `--wrapeffects never` could unexpectedly remove unrelated code, breaking the build.
Fixes #1776.
=> Fix issue where `--wrapeffects never` could unexpectedly remove unrelated code

Sources/FormattingHelpers.swift, Tests/RulesTests+Wrapping.swift
Follow-up to https://github.com/nicklockwood/SwiftFormat/pull/1778#discussion_r1693425905: the `--wrapeffects never` option shouldn't delete comments within the function declaration.
=> Update --wrapeffects never to not delete comments

Sources/DeclarationHelpers.swift, Sources/Rules.swift, Tests/RulesTests+Redundancy.swift
Adding exceptions to the `unusedPrivateDeclaration` rule
**`override`**
```swift
private class CustomClass: UIAccessibilityElement {
override private func accessibilityIncrement() { ... }
}
```
Overriden methods and properties are not used in the file but could be called by the base class.
**`@objc`, IBAction, IBSegueAction, IBOutlet, IBDesignable, IBInspectable, NSManaged, or GKInspectable attribute.**
You can access a private `@objc` Swift member via `Selector`. Also skipping any declarations with any of the above attributes.
To help figure out if a `Declaration` has an `@objc`, or any of the other attributes, I'm adding the following declaration helper
```swift
enum Declaration: {
...
var modifiers: [String] {
let parser = Formatter(openTokens)
guard let keywordIndex = parser.index(of: …
```
=> Add exceptions to unusedPrivateDeclaration rule

.github/workflows/build.yml, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat (Editor Extension).xcscheme, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat for Xcode.xcscheme
This PR adds CI jobs that build the following targets:
- SwiftFormat (Command Line Tool)
- SwiftFormat for Xcode
- SwiftFormat (Editor Extension)
We currently don't build these in CI, making it easy to break them on accident. I've done this twice recently, including today while working on the first draft of https://github.com/nicklockwood/SwiftFormat/pull/1782.
=> Build all targets in CI

Sources/DeclarationHelpers.swift
There is a typo in the [FocusState](https://developer.apple.com/documentation/swiftui/focusstate) SwiftUI property wrapper.
=> Fix focus state typo

Rules.md, Sources/DeclarationHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/MarkTypes.swift, Sources/Rules/OrganizeDeclarations.swift, Sources/Rules/SortDeclarations.swift, Tests/MetadataTests.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR updates the `organizeDeclarations` rule to avoid inserting blank lines inside consecutive groups of single-line properties.
For example, take this input:
```swift
class Foo {
init() {}
let foo: Foo
let baaz: Baaz
static let bar: Bar
}
```
Today, the reformatted output has a blank line that seems unnecessary:
```swift
class Foo {
// MARK: Lifecycle
init() {}
// MARK: Internal
static let bar: Bar
let foo: Foo
let baaz: Baaz
}
```
Now, we try to preserve the groupings in the original declaration. The output now feels more reasonable:
```swift
class Foo {
// MARK: Lifecycle
init() {}
// MARK: Internal
static let bar: Bar
let foo: Foo
let baaz: Baaz
}
```
-------
@miguel-jimenez-0529, I'm thinking this will fix the issue in #1794 where this input:
```swift
@Environment(\\.colorScheme) …
```
=> Update organizeDeclarations to avoid inserting blank lines inside consecutive groups of properties

Sources/DeclarationHelpers.swift, Tests/Rules/OrganizeDeclarationsTests.swift
There was a bug in the swiftUI property ordering flag where the properties are rearranged causing the synthesized member wise init to change breaking compilation.
cc: @calda
=> [iOS] Ensure SwiftUI property reorder doesn't affect synthesized init

Rules.md, Sources/Examples.swift, Sources/RuleRegistry.generated.swift, Sources/Rules/EmptyExtension.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/Rules/EmptyExtensionTests.swift, Tests/Rules/GenericExtensionsTests.swift, Tests/Rules/MarkTypesTests.swift, Tests/Rules/OpaqueGenericParametersTests.swift, Tests/Rules/TypeSugarTests.swift
Removes empty, non-conforming, extensions
```diff
-- extension String {}
--
extension String: Equatable {}
```
=> Add EmptyExtension rule+ tests

Sources/DeclarationHelpers.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR fixes an issue introduced by #1795 where a type's closing brace could unexpectedly turn into a comment if the type body ended with a comment.
For example, this sample code:
```swift
class Foo {
// MARK: Lifecycle
init() {}
// MARK: Internal
let bar: Bar
let baaz: Baaz
// Comment at end of file
}
```
was being unexpectedly changed to:
```swift
class Foo {
// MARK: Lifecycle
init() {}
// MARK: Internal
let bar: Bar
let baaz: Baaz
// }
```
=> Fix issue where closing brace could turn into a comment unexpectedly

Sources/DeclarationHelpers.swift, Sources/Rules/ExtensionAccessControl.swift, Sources/Rules/OrganizeDeclarations.swift, Sources/Rules/UnusedPrivateDeclaration.swift
Now that rules are defined in individual files, this PR moves many of the rule-specific helpers related to the `organizeDeclarations` rule from `DeclarationHelpers.swift` to `OrganizeDeclarations.swift`.
The helpers that remain in `DeclarationHelpers.swift` are more general, and most are used by more than one rule. I also improved many of these declarations, e.g. to extend `Declaration` rather than extending `Formatter` with the declaration passed in as an argument.
=> Move rule-specific helpers from DeclarationHelpers.swift to OrganizeDeclarations.swift, improve shared helpers

Rules.md, Sources/DeclarationHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/OrganizeDeclarations.swift, Tests/MetadataTests.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR enables the alphabetical sorting of SwiftUI property wrappers. This PR continues the implementation of https://github.com/nicklockwood/SwiftFormat/pull/1784 but I opened a new PR to prevent spending too much time fixing conflicts from `develop`.
```swift
// WRONG
struct ContentView: View {
@Environment(\\.colorScheme) var colorScheme
@State var foo: Foo
@Binding var isOn: Bool
@Environment(\\.quux) var quux: Quux
var body: some View {
Toggle(label, isOn: $isOn)
}
}
// RIGHT
struct ContentView: View {
@Binding var isOn: Bool
@Environment(\\.colorScheme) var colorScheme
@Environment(\\.quux) var quux: Quux
@State var foo: Foo
var body: some View {
Toggle(label, isOn: $isOn)
}
}
```
cc: @calda
=> Add SwiftUI properties subcategory alphabetical sort

README.md, Rules.md, Sources/Examples.swift, Sources/Formatter.swift, Sources/RuleRegistry.generated.swift, Sources/Rules/SpacingGuards.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/Rules/ElseOnSameLineTests.swift, Tests/Rules/HoistPatternLetTests.swift, Tests/Rules/IndentTests.swift, Tests/Rules/RedundantSelfTests.swift, Tests/Rules/RedundantStaticSelfTests.swift, Tests/Rules/SortSwitchCasesTests.swift, Tests/Rules/SpacingGuardsTests.swift, Tests/Rules/UnusedArgumentsTests.swift, Tests/Rules/WrapArgumentsTests.swift, Tests/Rules/WrapConditionalBodiesTests.swift
This is a fixed version of https://github.com/nicklockwood/SwiftFormat/pull/1801
Also added readme for https://github.com/nicklockwood/SwiftFormat/issues/1777
=> [New rule] spacingGuards

Sources/Rules/EmptyExtension.swift, Tests/Rules/UnusedPrivateDeclarationTests.swift
1. Adds `testRemoveUnusedRecursivePrivateDeclaration` test case to rule `unusedPrivateDeclaration` 
2. Fixes a small typo in EmptyExtension.swift
@calda
=> Add test case to unusedPrivateDeclaration

Sources/Arguments.swift, Sources/CommandLine.swift, Sources/Tokenizer.swift, Tests/CommandLineTests.swift
This PR adds a new `--outputtokens` CLI option that prints the output tokens, encoded as JSON, rather than printing the output source code. This only works when using stdin and stdout.
----
There's a specific use case I have in mind for this: at Airbnb we have an Xcode editor extension with a Format Swift command similar to [`FormatFileCommand.swift`](https://github.com/nicklockwood/SwiftFormat/blob/076525b91983bcd91f59367ed500b23d2a46c2e3/EditorExtension/Extension/FormatFileCommand.swift#L79). Instead of embedding the SwiftFormat framework in the app, we invoke the command line tool using stdin / stdout. This lets us use the same SwiftFormat version as whatever internal repo commit is checked out, rather than coupling the SwiftFormat version to the build of the app that contains the …
=> Add --outputtokens option to print output tokens instead of source code

Sources/DeclarationHelpers.swift, Sources/Rules/OrganizeDeclarations.swift, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat (Command Line Tool).xcscheme, Tests/Rules/OrganizeDeclarationsTests.swift
This PR fixes an issue where the `organizeDeclarations` rule would unexpectedly add extra blank lines due to spaces on blank lines in the file (e.g. `\n    \n` instead of `\n\n`).
This PR fixes #1809.
=> Fix issue where organizeDeclarations would add extra blank lines due to spaces on blank lines

Sources/ParsingHelpers.swift, Sources/Rules/UnusedArguments.swift, Tests/Rules/UnusedArgumentsTests.swift
This PR fixes https://github.com/nicklockwood/SwiftFormat/issues/1688#issuecomment-2282208032.
In this example, `lang` was incorrectly being marked as unused:
```swift
enum Sample {
func invite(lang _: String, randomValue: Int) -> String {
let flag: String? = if randomValue > 0 { "hello" } else { nil }
let lang = if let flag { flag } else { lang }
return lang
}
}
```
This was because `lang` was being added as a local from `let lang =` before we handled the `else { lang }` (which refers to the `lang: String` argument, not the `let lang =` local).
=> Fix issue where unusedArguments didn't handle conditional assignment shadowing

PerformanceTests/PerformanceTests.swift, Rules.md, Sources/Inference.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/SpaceAroundOperators.swift, Tests/ArgumentsTests.swift, Tests/InferenceTests.swift, Tests/Rules/SpaceAroundOperatorsTests.swift
This PR adds support for `--ranges preserve` and `--operatorfunc preserve` options.
This lets us adopt the SwiftFormat `spaceAroundRangeOperators` rule in Airbnb's Swift Style Guide. Previously we were using a set of four SwiftLint rules, but don't currently state a rule for spacing around range operators or in operator declarations.
=> Add `preserve` option to `spaceAroundRangeOperators` and `spaceAroundOperatorDeclarations`

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/OrganizeDeclarations.swift, Tests/Rules/OrganizeDeclarationsTests.swift
Adds a new way to sort SwiftUI properties, sorting them by the first time a property appears. This feature allow to still have custom sorting but requires that all SwiftUI properties of the same type are together.
```
/// WRONG
struct ContentView: View {
@Environment(\\.colorScheme) var colorScheme
@State var foo: Foo
@Binding var isOn: Bool
@Environment(\\.quux) var quux: Quux
var body: some View {
Toggle(label, isOn: $isOn)
}
}
/// RIGHT
struct ContentView: View {
@Environment(\\.colorScheme) var colorScheme
@Environment(\\.quux) var quux: Quux
@State var foo: Foo
@Binding var isOn: Bool
var body: some View {
Toggle(label, isOn: $isOn)
}
}
```
cc: @calda
=> Add option to sort SwiftUI properties by the first property appearance

Sources/Rules/RedundantVoidReturnType.swift, Tests/Rules/BlankLinesBetweenScopesTests.swift, Tests/Rules/RedundantVoidReturnTypeTests.swift
The existing rule doesn't remove redundant `Void` if the function is inside a protocol
```swift
// WRONG
protocol Foo {
func foo() -> Void
func bar() -> ()
var baz: Int { get }
func bazz() -> ( )
}
// RIGHT
protocol Foo {
func foo()
func bar()
var baz: Int { get }
func bazz()
}
```
cc: @calda
=>  Remove redundant Void from protocol definitions

.github/workflows/build.yml
https://github.com/nicklockwood/SwiftFormat/actions/runs/10539051276/job/29202226289?pr=1828
Apple Silicon delivers faster build times:
macOS | GHA Build
--- | ---
v12 | 9m44
v13 | 9m45
v14 | ___4m50___
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
=> GitHub Actions build on macOS v14 on AMD 64

.github/workflows/windows_release.yml, Platforms/Windows/SwiftFormat.wixproj, Platforms/Windows/SwiftFormat.wxs
We can't assume that SwiftFormat.exe will work with the Swift runtime installed on the user's machine (if there even is one), so the installer should package the runtime.
Also updates the github workflow to build with Swift 5.10.1 whose installer includes a redistributable.
Verified with a local build + installer build invocation.
=> Package Swift runtime with installer on Windows

Platforms/Windows/SwiftFormat.wxs
This directory structure is not natural on Windows, especially for installed apps. Changes the installer to put binaries directly into `C:\Program Files\nicklockwood\SwiftFormat`.
=> Windows installer: Avoid usr/bin directory structure

.github/workflows/windows_release.yml
=> Build the Windows installer for arm64 as well

.github/workflows/windows_release.yml
The build was failing because the path to the exe couldn't be found https://github.com/nicklockwood/SwiftFormat/actions/runs/10746115398/job/29806432973#step:6:232
The exe was being built under a path that included the default target triple instead of the arm64 one specified, because the target triple was passed to swiftc directly and bypassed SPM, which determines the output folder. The fix is to instead pass the target triple to SPM and let it forward it to swiftc.
=> Fix the arm64 release build workflow

.github/workflows/build.yml, .github/workflows/windows_release.yml
Adds a matrix to the Windows build workflow to build with two Swift versions: a minbar version and the version used by the release workflow, as we should avoid using a development snapshot if we can.
=> Change the Windows build workflow to use official Swift releases

.github/workflows/release.yml
When cutting new releases in https://github.com/calda/SwiftFormat/releases, we just tag some commit on `develop`. This means the [version number](https://github.com/nicklockwood/SwiftFormat/blob/main/Sources/SwiftFormat.swift#L35) in `SwiftFormat.swift` is incorrect, which causes occasionally issues with the cache (which is keyed off of this version number string).
The simplest fix is to automate this by making sure the version number in `SwiftFormat.swift` matches the name of the release. This is a no-op in the default case where the version number is already correct, like in this repo, but will help keep the workflow simple in custom cases like our release flow.
Using [this custom release](https://github.com/calda/SwiftFormat/releases/tag/0.55-custom-version-number-test-5) I confirmed …
=> Automatically use correct version number when building binaries for custom releases

README.md
We should probably update this badge to say Swift 5.3 instead of Swift 5.1
=> Update Swift badge in README to Swift 5.3

Rules.md, Sources/RuleRegistry.generated.swift, Sources/Rules/PrivateStateVariables.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/Rules/DocCommentsTests.swift, Tests/Rules/OrganizeDeclarationsTests.swift, Tests/Rules/PrivateStateVariablesTests.swift, Tests/Rules/UnusedPrivateDeclarationTests.swift, Tests/Rules/WrapAttributesTests.swift
Hi! I'm proposing this new rule, per Apple's recommendation that `@State` variables remain private to their view.
If desired, we could also expand this rule to cover other SwiftUI property wrappers that should be private, like `@Environment` and `@StateObject`
Feel free to close if you feel that this is too domain specific or too lint-y.
=> New rule: Adds `private` modifier to @State vars

Rules.md, Sources/FormatRule.swift, Sources/Rules/ApplicationMain.swift, Sources/Rules/BlankLinesBetweenChainedFunctions.swift, Sources/Rules/EnumNamespaces.swift, Sources/Rules/HeaderFileName.swift, Sources/Rules/LinebreakAtEndOfFile.swift, Sources/Rules/Linebreaks.swift, Sources/Rules/RedundantStaticSelf.swift, Sources/Rules/SortSwitchCases.swift, Sources/Rules/SortedImports.swift, Sources/Rules/SortedSwitchCases.swift, Sources/Rules/Specifiers.swift, Sources/Rules/TrailingSpace.swift, Sources/Rules/Wrap.swift, Sources/Rules/WrapSingleLineComments.swift, Sources/Rules/YodaConditions.swift
This PR makes the `examples` closure required for every FormatRule. In practice we want almost all rules to have an example.
This PR also adds an example for most of the rules that currently don't have one.
=> Make examples closure required for every FormatRule

README.md, Rules.md, Sources/Arguments.swift, Sources/CommandLine.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/RuleRegistry.generated.swift, Sources/Rules/NoFileID.swift, Sources/SwiftFormat.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/ArgumentsTests.swift, Tests/Rules/NoFileIDTests.swift
This PR adds a new `--languagemode` option to support specifying the Swift language mode. This will make it possible for us to add rules that depend on the language mode rather than a just minimum compiler version.
This PR also adds a small new rule that takes advantage of this: in Swift 6 mode, `#file` and `#fileID` have the same behavior, and `#file` is preferred over `#fileID`.
=> Add support for specifying Swift language mode

Sources/FormattingHelpers.swift, Tests/Rules/WrapConditionalBodiesTests.swift
We experienced a problem with the `wrapConditionalBodies` rule, where it would break compilation if a conditional body is inside a single line string as part of string interpolation.
I've fixed the issue and added test coverage. The fix is using the same check that was added to [fix an almost identical problem with ternary operator wrapping](https://github.com/nicklockwood/SwiftFormat/commit/cc885d7cfcb6f34527e8603888aa456cab9a872b).
=> Fix conditional body wrapping inside single line string interpolation

.github/workflows/build.yml, .gitignore, Sources/CommandLine.swift, Sources/GitFileInfo.swift, Sources/SwiftFormat.swift, Tests/Rules/FileHeaderTests.swift
Hello, I found some issues with git using the file header rule 🙂 
- Info not being fetched when using stdin (noticed when using the cli to lint in git hooks)
- Defaults not working when file is not committed (it should default to the current git user)
- Also added a test for this
- Checks for staged moved files so the git info can be properly fetched before committing 
- Currently it will be detected as a new file, and then after committing the change it will be properly followed
=> Git helpers improvements

Sources/ParsingHelpers.swift, Tests/Rules/WrapMultilineStatementBracesTests.swift
This PR fixes a regression in `wrapMultilineStatementBraces` that appears to be caused by https://github.com/nicklockwood/SwiftFormat/commit/71a08dd8816a190307c95d376716a325fe1b307f.
On `develop`, code like this:
```swift
extension Foo {
public func testWithWhereClause<A, B, Outcome>(
a: A,
b: B)
-> Outcome where
Outcome == (A, B)
{
return (a, b)
}
}
```
is currently being reformatted to:
```swift
extension Foo {
public func testWithWhereClause<A, B, Outcome>(
a: A,
b: B)
-> Outcome where
Outcome == (A, B) {
return (a, b)
}
}
```
=> Fix regression in `wrapMultilineStatementBraces` rule from bad `isStartOfClosure` result

Sources/DeclarationHelpers.swift, Sources/Rules/RedundantEquatable.swift, Tests/Rules/RedundantEquatableTests.swift
This PR updates the `redundantEquatable` rule to support nested types
=> Update redundantEquatable rule to support nested types

Sources/DeclarationHelpers.swift, Sources/Rules/EnvironmentEntry.swift, Tests/Rules/EnvironmentEntryTests.swift
This PR fixes some edge cases of the `environmentEntry` rule introduced in https://github.com/nicklockwood/SwiftFormat/pull/1908.
The fixes include:
- Allow enums as `EnvironmentKey`s
- Allow `let`s as the `EnvironmentKey.defaultValue`
- Allow direct value assignment of `EnvironmentKey.defaultValue`. (`static var defaultValue: Bool = true`)
- Allow `EnvironmentKey`s with any name as long as it is references in a `EnvironmentValues` property (`struct MyKey: EnvironmentKey`)
- Fix an issue where the `@Entry` macro was added after any access control modifier like `public`, `private`, etc.
cc: @calda
=> Fix environmentEntry edge cases

Sources/DeclarationHelpers.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR fixes #1907.
`--beforemarks` was unexpectedly checking function bodies for matching keywords, so in this example with `--beforemarks var,let` the `someInternalFunction` declaration was unexpectedly being included in `beforeMarks` (because its body contained the `let` keyword):
```swift
public final class Test: ObservableObject {
var someProperty: Int? = 0
func someInternalFunction() {
guard let someProperty: Int else {
return
}
print("Hello")
print("Hello")
print("Hello")
print("Hello")
print("Hello")
}
// MARK: - Public -
public func somePublicFunction() {
print("Hello")
print("Hello")
print("Hello")
print("Hello")
print("Hello")
}
// MARK: - Private -
private func somePrivateFunction() {
print("Hello")
print("Hello")
}
}
```
=> Fix issue where `--beforemarks` unexpectedly checked function bodies for matching keywords

.dockerignore, .github/workflows/docker.yml, CommandLineTool/main.swift, Dockerfile, Scripts/build-linux-release.sh
Partially fixes #1894 
`provenance: false` is for removing `unknown/unknown` from the OS/Arch tab here: https://github.com/nicklockwood/SwiftFormat/pkgs/container/swiftformat/272228423?tag=latest
Everything else should be self-explanatory.
Building for regular distribution on Linux could be done with the --output flag of docker build: https://docs.docker.com/build/building/export/
=> Use static Linux SDK in Dockerfile

README.md
I am proposing two changes to the documentation regarding Swift version specification.
_Firstly_, I suggest removing the recommendation to use `.swift-version`.  
I found no compelling reason to continue recommending this approach, especially since CocoaPods has not supported this file for [quite some time](https://blog.cocoapods.org/CocoaPods-1.7.0-beta/#:~:text=Finally%2C%20a%20warning%20will%20be%20displayed%20during%20lint%20that%20encourages%20pod%20authors%20to%20migrate%20away%20from%20using%20the%20.swift%2Dversion%20file%20and%20in%20a%20future%20major%20release%20of%20CocoaPods%20we%20plan%20to%20completely%20remove%20support%20for%20it.).  
If you know why this approach should be recommended, please let me know.
_Secondly_, I propose reordering the methods for specifying the …
=> Update documentation: equalize Swift Version Specification Methods

Sources/ParsingHelpers.swift, Sources/Rules/SortTypealiases.swift, Tests/Rules/SortTypealiasesTests.swift
As a follow-up to the fix for https://github.com/nicklockwood/SwiftFormat/issues/1929 this PR updates the `sortTypealaises` rule to support the `any` keyword.
=> Update `sortTypealiases` rule to support `any` keyword

Rules.md, Sources/RuleRegistry.generated.swift, Sources/Rules/PreferCountWhere.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/Rules/PreferCountWhereTests.swift
As suggested in https://github.com/nicklockwood/SwiftFormat/issues/1933, this PR adds a new `preferCountWhere` rule to prefer `count(where:)` over `filter(_:).count` calls in Swift 6.0+:
```diff
- planets.filter { !$0.moons.isEmpty }.count
+ planets.count(where: { !$0.moons.isEmpty })
- planets.filter { planet in
-     planet.moons.filter { moon in
-         moon.hasAtmosphere
-     }.count > 1
- }.count
+ planets.count(where: { planet in
+     planet.moons.count(where: { moon in
+         moon.hasAtmosphere
+     }) > 1
+ })
```
=> Add preferCountWhere rule

.github/workflows/release.yml
Added `-Osize` compiler optimization and a strip step for reducing binary size. Follows up on  https://github.com/nicklockwood/SwiftFormat/pull/1922#issuecomment-2489813740
=> Optimize macos binary size

Dockerfile
- fix: #1930 
- I had a problem that `swiftformat` command can fail with the image in 0.55.3
- I tried the new image on GitHub Actions workflow and found it works well
- https://github.com/ski-u/SwiftFormatWithGitHubActions/pull/7
=> Stop using busybox for docker

Rules.md, Sources/DeclarationV1.swift, Tests/Rules/OrganizeDeclarationsTests.swift
=> Update organizeDeclarations type mode to not treat properties with didSet as computed properties

Sources/Rules/OrganizeDeclarations.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR fixes an issue I noticed where the organizeDeclarations rule would unexpectedly remove a non-mark comment.
In this case, the comment is within the edit distance threshold of a comment like `// Static Properties`, meaning it would be unexpectedly removed:
```diff
enum Test {
-           /// Test Properties
static let foo = "foo"
static let bar = "bar"
static let baaz = "baaz"
}
```
Instead it seems better to only look for and remove MARK comments.
=> Fix issue where organizeDeclarations rule would unexpectedly remove non-mark comment

Rules.md
A code comment cage was leaking, so the next rule got put into the preceeding rules Example dropdown.
=> Fix leaking markdown code cage

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules/SwiftTesting.swift, Tests/Rules/SwiftTestingTests.swift
This PR fixes edge cases I noticed with the new `swiftTesting` rule that would cause build failures or runtime issues. For example:
- Adds `@Suite(.serialized)` by default to match the XCTest behavior where tests run serially by default. Existing tests may not expect to be ran concurrently. I saw issues related to this in Airbnb's test suite.
- Adds `import Foundation` by default, since XCTest exports `Foundation` (common for test cases to rely on Foundation types)
- Adds `import UIKit` if the file uses any UIKit symbols (common in tests for app codebases) since XCTest exports UIKit
- Fixed lots of issues where operators would cause build failures. Some examples of invalid code that we were generating before include `!foo == bar`, `!foo is Bar`, `try? foo == bar`, etc. (should be (`!(foo …
=> Fix edge cases with swiftTesting rule

Sources/Declaration.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR fixes a crash we found in the `organizeDeclarations` rule. 
As of the rewrite in https://github.com/nicklockwood/SwiftFormat/pull/1916 / https://github.com/nicklockwood/SwiftFormat/pull/1954, a `Declaration` is effectively a pointer to a subrange of the formatter's token array.
When sorting a type body, we have to update the range of each affected declaration to point to the correct range in the updated tokens. Previously we only handled this for declarations that were a direct child of the type being sorted. We also need to do this for any child declaration of one of those body declarations (in the case of nested types).
Without this the declaration references become invalid, and the bogus index values eventually cause issues elsewhere. To prevent that we now also assert that all …
=> Fix crash in organizeDeclarations rule to to invalidated declaration references

Sources/FormattingHelpers.swift, Sources/Rules/OrganizeDeclarations.swift, Sources/Rules/SortDeclarations.swift, Tests/MetadataTests.swift, Tests/Rules/OrganizeDeclarationsTests.swift, Tests/Rules/SortDeclarationsTests.swift
When sorting a type body with both `sortDeclarations` and `organizeDeclarations` are enabled, the `sortDeclarations` rule defers to the `organizeDeclararions` rule, which has a specialized sorting implementation.
However, the `orgganizeDeclarations` rule won't apply to any type below the configurable line count threshold. Since noth `sortDeclarations` and `organizeDeclarations` are disabled in this case, any `swiftformat:sort` would be ignored.
Now, the `sortDeclarations` rule checks whether the type is under the `organizeDeclarations` threshold, and if so will now sort the type body.
=> Fix issue where type under organizeDeclarations line count threshold would ignore `swiftformat:sort` directive

Dockerfile
We've started to experience some weird behavior with the newest releases of SwiftFormat (specifically related to #1930 and #1949). We have our own custom dockerfile layered on top of swiftformats that looks like this:
```dockerfile
FROM ghcr.io/nicklockwood/swiftformat:latest as swiftformat
FROM alpine:latest
LABEL description="Swiftformat image containing some additional utility binaries and our default format ruleset"
RUN apk add --no-cache bash
COPY company-swiftformat.sh /usr/bin/company-swiftformat.sh
COPY company-default-swiftformat-rules /etc/company-default-swiftformat-rules
COPY --from=swiftformat /usr/bin/swiftformat /usr/bin/swiftformat
WORKDIR /project
ENTRYPOINT ["/usr/bin/company-swiftformat.sh"]
CMD [ "." ]
```
That just adds a wrapper script and our default rules to the …
=> Use swift 6.0.3 toolchain in docker build

Sources/Rules/WrapMultilineFunctionChains.swift, Tests/Rules/WrapMultilineFunctionChainsTests.swift
Including a few more test cases
=> Improve handling of parenthesis and type access in new multiline function chains rule

Sources/DeclarationType.swift, Sources/Rules/BlankLinesAtStartOfScope.swift, Sources/Rules/ExtensionAccessControl.swift, Sources/Rules/SortDeclarations.swift, Tests/Rules/BlankLinesAtStartOfScopeTests.swift
This PR updates the `blankLinesAtStartOfScope` rule to support switch cases and closures with captures/params. Fixes #1996.
=> Update `blankLinesAtStartOfScope` rule to support switch cases and closures with captures/params

Sources/FormattingHelpers.swift, Sources/Inference.swift, Sources/ParsingHelpers.swift, Sources/Rules/Indent.swift, Tests/Rules/IndentTests.swift
This PR fixes the indentation of trailing closures after chained multiline method calls.
```swift
Foo()
.bar(
baaz: baaz,
quux: quux)
{
print("Trailing closure")
}
```
```swift
Foo()
.bar(
baaz: baaz,
quux: quux)
{
print("Trailing closure")
}
```
=> Fix indentation of trailing closures after chained multiline method calls

Rules.md, Sources/Rules/TrailingCommas.swift, Sources/SwiftFormat.swift, Tests/Rules/TrailingCommasTests.swift
This PR adds trailing commas for several new cases in [Swift 6.1](https://www.swift.org/blog/swift-6.1-released/): function and initializer parameters and arguments, `enum` case associated values.
It addresses these issues: [#1999](https://github.com/nicklockwood/SwiftFormat/issues/1999), [#1995](https://github.com/nicklockwood/SwiftFormat/issues/1995)
```
let foo: Foo = .init(
1
)
```
```
func foo(
bar _: Int
) {}
```
```
foo(
1
)
```
```
enum Foo {
case bar(
baz: String
)
}
```
```
let foo: Foo = .init(
1,
)
```
```
func foo(
bar _: Int,
) {}
```
```
foo(
1,
)
```
```
enum Foo {
case bar(
baz: String,
)
}
```
I'm planning to implement trailing commas for tuples, generic parameter lists, closure capture lists, and string interpolations in my next PRs.
=> Add trailing commas for new cases in Swift 6.1

Sources/FormattingHelpers.swift, Tests/Rules/RedundantSelfTests.swift
This PR fixes an issue where parameter packs could confuse the `redundantSelf` rule, causing it to throw an error. Fixes #1992.
=> Fix parameter pack parsing bug in redundantSelf rule

Sources/ParsingHelpers.swift, Tests/ParsingHelpersTests.swift
This PR updates the `parseType` and `parseExpressionRange` helpers to support parameter pack types and expressions, which start with `each` or `repeat each`.
=> Update parsing helpers to support parameter pack types and expressions

Sources/Tokenizer.swift, Tests/Rules/SpaceAroundOperatorsTests.swift, Tests/TokenizerTests.swift
This PR updates the tokenizer to support parameter pack syntax (`repeat each`) in generic angle brackets.
In an example like `Optional<(Wrapped, Other, repeat each Another)>` from #2000, the tokenizer was parsing the `<` as an operator instead of a `startOfScope`, because it was confused by the `repeat` keyword.
Fixes #2000.
=> Update tokenizer to support parameter pack syntax in generics

Rules.md, Sources/Rules/TrailingCommas.swift, Tests/Rules/TrailingCommasTests.swift
This PR adds support of trailing commas in all cases containing round parentheses `()` in [Swift 6.1](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0439-trailing-comma-lists.md)
Trailing commas were already supported in:
- Multi-line collections
- Parameter or argument lists
- Enum cases with associated values
Trailing commas are now **added** (or removed) for multi-line lists in the following contexts:
- Array and dictionary literals
- Function and initializer parameters and arguments
- Enum case associated values
- Tuple literals, including in `return`, `switch`, `case let`, `let`
- Parenthesized single expressions (e.g., `throw (error,)`, `if (true,)`, `guard (true,)`, `while (true,)`)
- Attribute arguments (e.g. `@Attribute(...)`)
- Macro arguments (e.g. …
=> Add support of trailing commas in all cases containing round parentheses in Swift 6.1

Sources/Rules/PropertyTypes.swift, Tests/Rules/PropertyTypesTests.swift
This PR fixes an issue where the `propertyTypes` rule could convert something like:
```swift
var scrollTargetBehavior: (some ScrollTargetBehavior) = .paging
```
to:
```swift
var scrollTargetBehavior: (some ScrollTargetBehavior).paging
```
which no longer compiles, since you can't use static member lookup on a `some` type like this.
We need to handle `some` like how we handle `any`.
=> Fix issue where propertyTypes rule could break property using some keyword

Sources/Formatter.swift, Tests/FormatterTests.swift
This PR updates fatal error messages to include the current rule name. This will make it easier to diagnose issues like #1992, where a specific rule was crashing the formatter.
Before:
```
error: The static modifier is not valid outside a type body on line 56 in /Users/cal/Downloads/Calligraphy/Sources/Calligraphy/DirectoryContentBuilder.swift
```
After:
```
error: [redundantSelf] The static modifier is not valid outside a type body on line 56 in /Users/cal/Downloads/Calligraphy/Sources/Calligraphy/DirectoryContentBuilder.swift
```
=> Update fatal error messages to include rule name

Sources/FormattingHelpers.swift, Tests/Rules/WrapArgumentsTests.swift
This PR fixes support for using `--callsiteparen balanced` with `--closingparen same-line`. Previously this configuration would result in the `--callsiteparen balanced` option having no effect.
=> Fix support for `--closingparen same-line` `--callsiteparen balanced`

Rules.md, Sources/Rules/Acronyms.swift, Tests/Rules/AcronymsTests.swift
This PR updates the acronyms rule to respect the `--preservedsymbols` option. Symbols included there will not be autocorrected. Fixes https://github.com/nicklockwood/SwiftFormat/issues/2019.
=> Update acronyms rule to respect list of `--preservedsymbols`

.github/workflows/release.yml
The Linux release build is failing because `ubuntu-20.04` support has been removed. This PR updates the job to `ubuntu-latest`. Tested the job here, which passed: https://github.com/nicklockwood/SwiftFormat/actions/runs/14840548772
Fixes https://github.com/nicklockwood/SwiftFormat/issues/2023
=> Fix Linux release build

Sources/ParsingHelpers.swift, Sources/Rules/OpaqueGenericParameters.swift, Tests/ParsingHelpersTests.swift
This PR improves the `parseFunctionDeclaration` to handle `subscript` and `init` declarations, and adopts it in the `opaqueGenericParameters` rule, which previously implemented most of the same parsing.
=> Improve `parseFunctionDeclaration` helper, adopt in `opaqueGenericParameters` rule

Tests/Rules/WrapArgumentsTests.swift
This PR adds more test cases for the `wrapArguments` rule, testing cases like `init`, `subscript`, and functions with no return type.
=> Add more wrapArguments test cases

Sources/Declaration.swift, Sources/Formatter.swift, Sources/FormattingHelpers.swift, Sources/Rules/OpaqueGenericParameters.swift, Tests/Rules/OpaqueGenericParametersTests.swift, Tests/Rules/SortDeclarationsTests.swift
`Declaration`s are a dynamic, auto-updating reference to a subrange of indices within a `Formatter`. This is helpful because it lets you avoid invalidating existing indices, or having to manually increment/decrement index values while making changes.
This PR generalizes that auto-updating functionality into `AutoUpdatingIndex` and `AutoUpdatingRange` values that can be used within other rules.
=> Add AutoUpdatingIndex and AutoUpdatingRange based on existing auto-updating Declaration functionality

Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules/DocComments.swift, Tests/ParsingHelpersTests.swift, Tests/Rules/OpaqueGenericParametersTests.swift, Tests/Rules/WrapArgumentsTests.swift
This PR fixes some new bugs that I noticed in the current set of changes on develop
1. `formatter.endOfDeclaration` would unexpectedly return `nil` for the last declaration in a type body. This was causing `parseFunctionDeclaration` to return `bodyRange: nil` in this case, which could cause build failures in the `opaqueGenericParameters` rule.
2. `--wrapreturntype if-multiline` is now applied to closure types, now that the implementation no longer requires the scope to have a body with a `{` token. This was causing an interaction with the open paren wrapping that looked weird and unnecessary.
```swift
// Before
var foo: (
(
Any?,
Bool,
TimeInterval,
String,
Int,
String)
-> Void)?
// With this fix
var foo: ((
Any?,
Bool,
TimeInterval,
String,
Int,
String)
-> Void)?
```
=> Fix some new bugs on develop branch

CONTRIBUTING.md, README.md
This PR adds a section about the new nightly build setup in [calda/SwiftFormat-nightly](https://github.com/calda/SwiftFormat-nightly) to the README
=> Add section about nightly builds to README

CONTRIBUTING.md, README.md
The Homebrew` --HEAD` option now points to the `develop` branch: https://github.com/Homebrew/homebrew-core/pull/222602#event-17589967153
This lets users more easily download, build, and install the latest changes from the `develop` branch.
This PR adds discussion about that to the README.
=> Add section about Homebrew --HEAD option

CONTRIBUTING.md, SwiftFormat.xcodeproj/project.pbxproj, SwiftFormat.xcodeproj/xcshareddata/xcschemes/Performance Tests.xcscheme, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat (Command Line Tool).xcscheme, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat (Editor Extension).xcscheme, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat (Framework).xcscheme, SwiftFormat.xcodeproj/xcshareddata/xcschemes/SwiftFormat for Xcode.xcscheme
Currently building release builds of the command line tool in Xcode requires a signing certificate.
Builds produced from the command line with `swift build -c release` don't need to be signed. That made me realize we can just remove the "Team" and "Signing Certificate" requirement.
Release builds and Product > Archive still work correctly.
=> Remove need for signing certificate when building release builds of command line tool in Xcode

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/Acronyms.swift, Tests/Rules/AcronymsTests.swift
=> Update `acronyms` rule to use `--preserveacronyms` option instead of `--preservedsymbols`

Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Tests/ParsingHelpersTests.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR fixes an issue where `organizeDeclarations` would break if the code included a property like:
```swift
private lazy var x: [Any] =
if let b {
[b]
} else if false {
[]
} else {
[1, 2]
}
```
The `let` keyword in `if let b` was being confused for a subsequent `let b` declaration. 
Fixes #2045.
=> Update `organizeDeclarations` / `parseDeclarations` to support property declarations with if expression values

Sources/ParsingHelpers.swift, Tests/Rules/WrapArgumentsTests.swift
This PR fixes an issue where the `--wrapeffects` option would incorrectly unwrap `async let` properties following a function call.
Fixes #2044.
=> Fix issue where `--wrapeffects` option would incorrectly unwrap `async let` properties following function call

Sources/ParsingHelpers.swift, Tests/Rules/ExtensionAccessControlTests.swift
This PR fixes an issue where the `extensionAccessControl` rule didn't handle `@preconcurrrency` conformances.
Fixes #2042.
=> Fix issue where `extensionAccessControl` rule didn't handle `@preconcurrrency` conformances

Sources/ParsingHelpers.swift, Sources/Rules/PropertyTypes.swift, Sources/Rules/RedundantEquatable.swift, Tests/ParsingHelpersTests.swift, Tests/Rules/RedundantEquatableTests.swift
This PR fixes an issue where the `redundantEquatable` rule would incorrectly remove the `==` implementation in cases like:
```swift
struct Foo: Equatable {
let tupleValue: (string: String, int: Int)
static func == (lhs: Foo, rhs: Foo) -> Bool {
lhs.tupleValue == rhs.tupleValue
}
}
```
Since tuples aren't Equatable, the compiler doesn't automatically synthesize an Equatable conformance.
This also applies to some built-in types like `AnyClass`. Eventually we may want an option to let consumers provide more non-Equatable types like this, but let's start with a hard-coded list until somebody asks for it.
Fixes https://github.com/nicklockwood/SwiftFormat/issues/2043
=> Update `redundantEquatable` rule to handle non-Equatable types with == support like tuples

.github/workflows/windows_release.yml
This PR updates the windows release job to be ran automatically when making a new release, and upload the resulting artifacts directly to the release. 
I tested this in my fork and validated that it woks correctly:
=> Update windows job to automatically upload release artifacts

Rules.md, Sources/Arguments.swift, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules/Wrap.swift, Sources/Rules/WrapArguments.swift, Tests/CommandLineTests.swift, Tests/MetadataTests.swift, Tests/Rules/WrapTests.swift
We've found that line wrapping within string interpolation is often unintuitive and sometimes produces strange results. This PR adds a `--wrapstringinterpolation preserve` option that disables wrapping within string interpolation. 
I chose `preserve` instead of `false` or `never` to leave open the future direction of having `false` or `never` _remove_ line breaks within string interpolation (that's what `wrap: never` does in other existing options).
=> Add option to disable line wrapping within string interpolation

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/BlankLinesAfterGuardStatements.swift, Tests/Rules/BlankLinesAfterGuardStatementsTests.swift
This PR adds `--linebtwnguards` option to `blankLinesAfterGuardStatements` rule which allows inserting/leaving one blank line between consecutive guards. The option name was chosen to match the style already written, such as `--lineaftermarks` in `blankLinesAroundMark` rule.
Example:
`--linebtwnguards false` (default)
```diff
guard let spicy = self.makeSpicy() else {
return
}
-
guard let soap = self.clean() else {
return
}
+
let doTheJob = nikekov()
```
`--linebtwnguards true`
```diff
guard let spicy = self.makeSpicy() else {
return
}
guard let soap = self.clean() else {
return
}
+
let doTheJob = nikekov()
```
It would be great to have this feature in SwiftFormat by default :)
=> Add option to `blankLinesAfterGuardStatements` rule to have blank line between consecutive guards

Rules.md, Sources/Arguments.swift, Sources/CommandLine.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/BlankLinesAfterGuardStatements.swift, Sources/Rules/ConditionalAssignment.swift, Sources/Rules/OrganizeDeclarations.swift, Sources/Rules/PreferForLoop.swift, Sources/Rules/PropertyTypes.swift, Sources/Rules/SortDeclarations.swift, Sources/Rules/WrapAttributes.swift, SwiftFormat.xcodeproj/project.pbxproj, Tests/CommandLineTests.swift, Tests/MetadataTests.swift, Tests/Rules/PropertyTypesTests.swift
This PR removes the 16 character limit for option names and the 80 character limit for option descriptions.
This was originally to keep the help text output under 80 characters wide. Instead, this PR updates the help text formatting to use the style used by `swift --help`:
- For short option names, the description is output on the same line.
- For long option names, the description is output with indentation on the following line.
For example:
```
--option           Short option description
--option           Short option description
--optionmedium     Option with a medium name and description length
--optionmedium     Option with a medium name and description length
--optionwithlongername
This is a longer option with a name over the original 16 character limit, and a help text over the …
```
=> Update help formatting to support options with longer names and descriptions, remove character limit

Sources/ParsingHelpers.swift, Sources/Rules/TrailingCommas.swift, Tests/Rules/TrailingCommasTests.swift
This PR fixes more Swift 6.1 edge cases with the `trailingCommas` rule:
- It was mistaking `@escaping` and `@Sendable` closures for an attribute with arguments in parenthesis rather than a closure type
- It thought that trailing commas were supported in `protocol` primary associated type lists, even though this is unexpectedly not supported in Swift 6.1
Fixes https://github.com/nicklockwood/SwiftFormat/issues/2061.
=> Update `trailingCommas` to support `@escaping` / `@Sendable` closures, protocol primary associated types

.github/workflows/build.yml, CONTRIBUTING.md, Scripts/test.sh, Scripts/test_rule.sh, SwiftFormat.xcodeproj/project.pbxproj
This PR updates the project to support adding and testing new rules without using Xcode, by:
1. Updating the `Rules` folders in the Xcode project from groups to folder references. This make it so you can add new rules just by creating files on disk without having to modify the Xcode project.
2. Adding a `./Scripts/test_rule.sh` script for running the tests for an individual rule (e.g. `./Scripts/test_rule.sh blankLinesAtStartOfScope`).
=> Support adding and testing new rules without using Xcode

Sources/Rules/PrivateStateVariables.swift, Tests/Rules/PrivateStateVariablesTests.swift
Fixes this issue:
https://github.com/nicklockwood/SwiftFormat/issues/2063
Excludes `@Previewable` `@State` property wrappers from the "private state" rule, even if the `@Previewable` and `@State` tokens are on separate lines.
=> Fix private state rule for when Previewable is on previous line

Sources/Arguments.swift, Sources/CommandLine.swift, Sources/Formatter.swift, Sources/Options.swift, Sources/Rules/ExtensionAccessControl.swift, Sources/Rules/Indent.swift, Sources/Rules/OrganizeDeclarations.swift, Sources/SwiftFormat.swift, Tests/CommandLineTests.swift, Tests/ParsingHelpersTests.swift
This PR adds support for formatting code blocks in markdown files. You can pass in either:
- `--markdownfiles format-strict`, to require that all markdown code blocks parse and format successfully
- `--markdownfiles format-lenient`, to only format code blocks that parse and format without encountering errors
It also supports providing additional SwiftFormat options in the code block header, including `no-format` to have the block not be formatted or parsed at all.
For example, this markdown input:
> ### Sample README
> 
> This is a nice project with lots of cool APIs to know about, including:
> 
> ```swift
> func foo(
> bar: Bar,
> baaz: Baaz
> ) -> Foo { ... }
> ```
> 
>   Uses `--indent 2`:
>   ```swift --indent 2
>   func foo(
>   bar: Bar,
>   baaz: Baaz
>   ) -> Foo { ... }
>   ```
> …
=> Add support for formatting code blocks in markdown files

.github/workflows/validate_pr.yml
This PR adds a GitHub actions job to validate that a PR's base branch is `develop`.
For example, on a PR targeting `main`:
and a PR targeting `develop`:
=> Add job to validate that PR base branch is `develop`

Sources/Rules/TrailingCommas.swift, Tests/Rules/TrailingCommasTests.swift
This PR fixes Swift 6.1 trailing support for closure / tuple typealiases. We were mistaking these types for expressions (where trailing commas are allowed in 6.1) since they were on the RHS of an `=` assignment.
Fixes #2071.
=> Fix Swift 6.1 trailing comma support for closure / tuple typealiases

Sources/Declaration.swift, Sources/Formatter.swift, Sources/Rules/ModifiersOnSameLine.swift, Sources/Rules/RedundantEquatable.swift, Tests/Rules/ModifiersOnSameLineTests.swift
This PR fixes some edge case in the new `modifiersOnSameLine` rule:
1. Don't unwrap if it would cause the `maxWidth` to be exceeded
2. Avoid confusing identifiers in previous declarations with modifiers, like in:
```swift
@Environment(\.rowPaddingOverride) private var override
private var resolvedRowPadding: AdaptiveEdgeInsets
// This was being unwrapped to:
@Environment(\.rowPaddingOverride) private var override private var resolvedRowPadding: AdaptiveEdgeInsets
```
=> Fix edge cases in `modifiersOnSameLine` rule

Rules.md, Sources/ParsingHelpers.swift, Sources/RuleRegistry.generated.swift, Sources/Rules/ThrowingTests.swift, Tests/CodeOrganizationTests.swift, Tests/MetadataTests.swift, Tests/Rules/PreferSwiftTestingTests.swift, Tests/Rules/ThrowingTestsTests.swift
`try!` is always bad. In Unit tests, we can just make the test function `throws` and automatically remove them. 
This is a draft until I also implement the XCTest version
=> Prefer throwing tests to using `try!`

Sources/Rules/DocComments.swift, Tests/Rules/DocCommentsBeforeModifiersTests.swift
The `docComments` rule will occasionally time out when processing very long comments. We found a file with 900+ lines of commented-out code where `docComments` was consistently taking 15-20 seconds to run.
We were previously doing a lot of repeated work at each comment index, so we can improve performance by avoiding that. Now the long file can be formatted / linted in ~0.1-0.2s.
=> Improve performance of `docComments` rule

Sources/Rules/DocComments.swift, Tests/Rules/DocCommentsTests.swift
I noticed a new issue where trailing comments were being converted to doc comments:
```diff
// Comment
- let foo: Foo // Foo
+ let foo: Foo /// Foo
let bar: Bar // Bar
```
This PR fixes the issue
=> Fix bug where trailing comments would be converted to doc comments

Sources/Rules/Void.swift, Tests/Rules/VoidTests.swift
This PR update the `void` rule to convert `()` to `Void` in typealiases, since `()` represents a type in this case.
=> Update `void` rule to convert `()` to `Void` in typealiases

PerformanceTests/PerformanceTests.swift, Rules.md, Sources/Declaration.swift, Sources/FormattingHelpers.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules/BlankLinesAtEndOfScope.swift, Sources/Rules/BlankLinesAtStartOfScope.swift, Tests/Rules/BlankLinesAtEndOfScopeTests.swift, Tests/Rules/BlankLinesAtStartOfScopeTests.swift, Tests/XCTestCase+testFormatting.swift
This pull request introduces a new formatting rule, `breakLineAtEndOfTypes`, to enforce a blank line before the closing brace of type declarations (e.g., `class`, `struct`, `enum`). It includes updates to the core formatting logic, configuration options, and test cases, as well as project file changes to integrate the new rule.
* Added a new rule, `breakLineAtEndOfTypes`, to ensure a blank line exists before the closing brace of type declarations. This rule supports types such as `class`, `struct`, `enum`, `protocol`, `extension`, and `actor`. (`Sources/Rules/BreakLineAtEndOfTypes.swift`)
* Introduced a new `breakLineAtEndOfTypes` property in the `FormatOptions` struct to enable or disable the rule. Default value is `false`. (`Sources/Options.swift`) …
=> Add breakLineAt End & Start OfScope rule

PerformanceTests/PerformanceTests.swift, Rules.md, Sources/FormattingHelpers.swift, Sources/Inference.swift, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/ParsingHelpers.swift, Sources/Rules/Indent.swift, Sources/Rules/TrailingCommas.swift, Tests/InferenceTests.swift, Tests/Rules/TrailingCommasTests.swift, Tests/Rules/WrapArgumentsTests.swift
Hello!
I've taken a crack at a fix for https://github.com/nicklockwood/SwiftFormat/issues/2053 and added a new `commas` rule option: `collections`, to supplement the existing `inline` and `always` options.
Not sure I love the implementation currently as it starts conflating language level support with rule configuration and I'm curious to hear if y'all have any thoughts. (It seems to work but it may be difficult to extend further to additional options in the future)
- Is this generally something y'all would be open to supporting?
- Any suggestions on the testing strategy? My current approach was to add a second assert within each 6.1 specific test that ensures that `collections` "undoes" `always` to avoid duplicating lots of string literals.
=> Add support for opting-out of Swift 6.1 trailing comma support.

Rules.md, Sources/Rules/TrailingCommas.swift
Rules doc missed a code closing tag
=> Add missing code tag to Rules documentation 

Sources/Arguments.swift, Sources/CommandLine.swift, Sources/Options.swift, Sources/SwiftFormat.swift, Tests/CommandLineTests.swift
This PR updates the `--config` option to support multiple config files. For example, you could have a base `A.swiftformat` file, and a separate `B.swiftformat` with overrides. Now `--config A.swiftformat --config B.swiftformat` handles this use case.
I actually always thought this was how it worked! I was trying to use this locally and found out that it didn't actually work this way. Seems like a nice enhancement for flexibility.
=> Support multiple `--config` files

Rules.md, Snapshots/Layout/Layout/Utilities.swift, Sources/RuleRegistry.generated.swift, Sources/Rules/RedundantMemberwiseInit.swift, Tests/Rules/BlankLinesBetweenScopesTests.swift, Tests/Rules/RedundantMemberwiseInitTests.swift, Tests/Rules/RedundantPublicTests.swift, debug_test.swift
This rule removes an explicit initializer from structs when the initializer can be syntetized by the compiler, therefore the init becomes redundant. 
```diff
struct Person {
var name: String
var age: Int
-   init(name: String, age: Int) {
-       self.name = name
-       self.age = age
-   }
}
```
=> Add Redundant struct Member wise Init rule

Sources/Rules/RedundantMemberwiseInit.swift, Tests/Rules/RedundantMemberwiseInitTests.swift
This commit fixes the handling of public structs in the redundantMemberwiseInit rule:
- Fix access level logic: preserve public inits in public structs, remove internal inits from public structs
- Add comprehensive test coverage for public struct scenarios
- Add test for private init preservation in internal structs
Key fixes:
- Internal inits in public structs are now correctly removed (compiler generates internal memberwise init)
- Public inits in public structs are preserved (explicit public API)
- Private inits in internal structs are preserved (maintain access level restrictions)
The rule now correctly handles the Swift compiler's memberwise init generation rules:
- Compiler never generates public memberwise inits
- Internal inits in public structs are redundant with …
=> Fix public struct handling in redundantMemberwiseInit rule

Rules.md, Sources/Arguments.swift, Sources/OptionDescriptor.swift, Sources/Rules/URLMacro.swift, Tests/ArgumentsTests.swift
We noticed that adding `--urlmarco "#URL,URLFoundation"` in config files didn't work properly, because the `#` within the string literal wasn't being escaped, and was being treated as the start of a comment.
This PR fixes the issue so `#` can be escaped in config files.
=> Support escaping `#` characters in config files

Sources/ParsingHelpers.swift, Tests/Rules/RedundantEquatableTests.swift, Tests/Rules/URLMacroTests.swift
If you have markdown like:
````md
```swift
AsyncImage(url: URL(string: "https://mysite.com/image.png")!)
```
````
the `urlMacro` rule with `--urlMacro "#URL,URLFoundation"` currently converts this to:
````md
```swift
import URLFoundation
AsyncImage(url: #URL(string: "https://mysite.com/image.png"))
```
````
Since we're inside a markdown code block fragment, the import is unnecessary.
This PR updates the `addImports` helper to do nothing when inside fragments like this. This way, the markdown is instead updated to:
````md
```swift
AsyncImage(url: #URL(string: "https://mysite.com/image.png"))
```
````
=> Update `urlMacro` and `redundantEquatable` rules to not add imports in code fragments

Sources/Arguments.swift, Tests/ArgumentsTests.swift
=> Fix config file generation in SwiftFormat for Xcode app to escape options with # character in quotes

README.md
This PR adds documentation about the new markdown code block formatting support
-------
Markdown formatting
-------------------
SwiftFormat can format Swift code blocks inside Markdown files (`.md`). This is useful for keeping code examples in documentation, README files, and other markdown content properly formatted.
````diff
This is a nice project with lots of cool APIs to know about, including:
```swift
func foo(
- bar: Bar,
- baaz: Baaz
+     bar: Bar,
+     baaz: Baaz
) -> Foo { ... }
```
````
To format Swift code blocks in markdown files, use the `--markdownfiles` option with either `format-strict` or `format-lenient`:
```bash
$ swiftformat . --markdownfiles format-strict
$ swiftformat . --markdownfiles format-lenient
```
Or add it to your `.swiftformat` config file:
``` …
```
=> Add documentation about markdown formatting support

README.md, Sources/Formatter.swift, Sources/FormattingHelpers.swift, Sources/Inference.swift, Sources/ParsingHelpers.swift, Tests/FormatterTests.swift
This PR refactors the way that `swiftformat:` comment directives are processed so that we can support `:this` and `:previous` in addition to `:next` (a [frequently](https://github.com/nicklockwood/SwiftFormat/issues/2097) [requested](https://github.com/nicklockwood/SwiftFormat/issues/1753) [feature](https://github.com/nicklockwood/SwiftFormat/issues/2001)).
=> Support :this and :previous in comment directives

Sources/Rules/WrapEnumCases.swift, Tests/Rules/WrapEnumCasesTests.swift
This PR updates the `wrapEnumCases` rule to use `parseDeclarations()`. This gives us a reliable end index for the `case` declaration, which makes it easier to parse the individual case identifiers.
Fixes #2128.
=> Update `wrapEnumCases` rule to use `parseDeclarations()`

Sources/FormattingHelpers.swift, Tests/Rules/WrapArgumentsTests.swift
This PR updates `--wrap-return-type never` to work with `--allman true`.
Fixes #2131
=> Update `--wrap-return-type never` to work with `--allman true`

Sources/Rules/RedundantPublic.swift, Tests/Rules/RedundantPublicTests.swift
This PR fixes an issue where `redundantPublic` rule didn't handle extensions on types defined in public extensions.
Fixes #2136.
=> Fix issue where `redundantPublic` rule didn't handle extensions on types defined in public extensions

README.md
I noticed the Swift version badge in the README was outdated. I considered performing an in-place update of the version, but figured I'd offer a solution that doesn't need to be continuously updated: this change proposes updating the Swift badge to use Swift Package Index's badge that dynamically computes the supported Swift versions via nightly builds.
I also updated the link to lead to Swift Package Index rather than the Swift website as well, to show the source of the new badge. Happy to revert any part of this PR that isn't wanted.
=> Use swift package index badge for supported swift version

Sources/Rules/TrailingCommas.swift, Tests/Rules/TrailingCommasTests.swift
This PR fixes #2142 and #2143.
In cases where we don't know whether or not a trailing comma is supported, we previously would always remove the comma. This resulted in false negatives (#2142). Instead, we should preserve the comma in these cases.
Also, this PR fixes support for inserting trailing commas in function declarations with generic parameters.
=> Update `--trailing-commas always` to preserve trailing commas even when not known to be supported by Swift 6.1

Sources/Arguments.swift, Tests/CommandLineTests.swift
This PR fixes a spurious `--commas option is deprecated. Use '--trailingcommas' instead` warning when using `--trailing-commas collections-only`.
Fixes https://github.com/nicklockwood/SwiftFormat/issues/2141
=> Fix spurious `--commas option is deprecated. Use '--trailingcommas' instead` warning

Sources/FormattingHelpers.swift, Sources/Rules/SpaceAroundBrackets.swift, Tests/Rules/HoistTryTests.swift, Tests/Rules/SpaceAroundBracketsTests.swift
This PR fixes an issue where the `hoistTry` rule could break `@Test` attributes containing `try`.
Fixes #1985.
=> Fix issue where `hoistTry` rule could break @Test attributes containing `try`

Sources/Rules/RedundantVoidReturnType.swift, Tests/Rules/RedundantVoidReturnTypeTests.swift
This PR fixes an issue where the `redundantVoidReturnType` rule could accidentally remove a closure return type, since it was confusing the `-> ()` for a void return.
Fixes #1978.
=> Fix issue where `redundantVoidReturnType` rule accidentally removed closure return type

Sources/DeclarationType.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR updates `organizeDeclarations` to treat `associatedtype` declarations as nested types, like `typealias` declarations.
This makes the rule property support `protocol`s.
=> Update `organizeDeclarations` to treat `associatedtype` declarations as nested types, like `typealias` declarations.

Sources/Rules/OrganizeDeclarations.swift, Tests/Rules/OrganizeDeclarationsTests.swift
Before, the `organizeDeclarations` rule would add access control marks to protocols:
```swift
public protocol Foo {
// MARK: Lifecycle 
init()
// MARK: Internal 
func foo()
func bar()
}
```
This is wrong, because these declarations are public, not internal. This also only happens if the protocol includes `init()` requirements, otherwise all declarations would be in the same category.
Instead of making this `// MARK: Public`, let's just omit the marks:
```swift
public protocol Foo {
init()
func foo()
func bar()
}
```
=> Don't add access control marks in protocol bodies

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/OrganizeDeclarations.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR adds threshold-based options for organizing type bodies without adding `// MARK` comments.
For example, for structs under 20 lines, you may want to organize the type body, but not add `// MARK` comments.
=> Add `organizeDeclarations` threshold options to organize types without adding marks

.github/workflows/notarize.yml, CONTRIBUTING.md, SwiftFormat.xcodeproj/project.pbxproj
This PR adds a GitHub action job to build, sign, and notarize the SwiftFormat for Xcode app. This runs automatically for a new release.
Example notarized app:
[SwiftFormat-for-Xcode.zip](https://github.com/user-attachments/files/21415657/SwiftFormat-for-Xcode.zip)
=> Set up job to build and notarize SwiftFormat for Xcode

Rules.md, Sources/FormattingHelpers.swift, Sources/ParsingHelpers.swift, Sources/Rules/SwiftTestingTestCaseNames.swift, Sources/Tokenizer.swift, Tests/Rules/PropertyTypesTests.swift, Tests/Rules/RedundantBackticksTests.swift, Tests/Rules/SwiftTestingTestCaseNamesTests.swift, Tests/TokenizerTests.swift
This PR adds support for Swift 6.2 raw identifiers: https://github.com/swiftlang/swift-evolution/blob/main/proposals/0451-escaped-identifiers.md
Fixes https://github.com/nicklockwood/SwiftFormat/issues/2093.
=> Add support for Swift 6.2 raw identifiers

RegressionTests/RegressionTests.swift, Rules.md, Snapshots/Expression/Sources/Expression.swift, Snapshots/Issues/697.swift, Sources/Rules/RedundantPublic.swift, Tests/Rules/RedundantPublicTests.swift
This PR updates the `redundantPublic` rule to apply to `private` types, rather than only `internal` types. Not sure why I didn't include this in the original implementation.
=> Update `redundantPublic` rule to apply to private types

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/Rules/OrganizeDeclarations.swift, Tests/Rules/OrganizeDeclarationsTests.swift
This PR adds a `--type-body-marks remove` option to the `organizeDeclarations` rule.
When enabled, it removes MARK comments in type bodies, other than the ones added automatically: 
- `// MARK: Lifecycle`
- `// MARK: Public`
- `// MARK: Internal`
- `// MARK: Private`
- etc
=> Add `--type-body-marks remove` option to `organizeDeclarations`

Sources/Rules/PropertyTypes.swift, Sources/TypeName.swift, Tests/Rules/PropertyTypesTests.swift
This PR updates the `propertyTypes` rule to support `Set` literal initialization, like it does with arrays and dictionaries as of https://github.com/nicklockwood/SwiftFormat/pull/2185.
=> Update `propertyTypes` rule to support `Set` literal initialization, like with arrays and dictionaires

Rules.md, Sources/ParsingHelpers.swift, Sources/Rules/TrailingClosures.swift, Tests/Rules/TrailingClosuresTests.swift
This PR updates the `trailingClosures` rule to support multiple trailing closures. If the first closure doesn't have a label, we convert the function call to use multiple trailing closure syntax:
```diff
- withAnimation(.spring, {
-   isVisible = true
- }, completion: {
-   handleCompletion()
- })
+ withAnimation(.spring) {
+   isVisible = true
+ } completion: {
+   handleCompletion()
+ }
```
=> Update `trailingClosures` rule to support multiple trailing closures

Rules.md, Sources/Declaration.swift, Sources/ParsingHelpers.swift, Sources/RuleRegistry.generated.swift, Sources/Rules/PreferFinalClasses.swift, Tests/ParsingHelpersTests.swift, Tests/Rules/PreferFinalClassesTests.swift, Tests/XCTestCase+testFormatting.swift
This PR adds a new `preferFinalClasses` rule that adds the `final` keyword to non-`open` classes.
The rule includes some heuristics to avoid adding `final` in cases where they may be existing subclasses:
1. We check if there are any subclasses within the file itself
2. We check if the type name contains "Base" -- this is a common pattern for indicating that the type will be subclasses
=> Add `preferFinalClasses` rule

Sources/Rules/BlankLinesAroundMark.swift, Tests/Rules/BlankLinesAroundMarkTests.swift
Fixes #2202 
This fixes an issue where `blankLinesAroundMark` wouldn't ignore trailing comments at the start of scope. 
`blankLinesAroundMark` is configured to not add a blank line at the start of scope, so this wouldn't produce a lint warning:
```
struct Example {
// MARK: Properties
let value: String
}
```
However, if there's a trailing comment at the start of scope, this would produce a lint warning.
```
struct Example { // some comment
// MARK: Properties
let value: String
}
```
The trailing comment at the start of scope shouldn't affect whether a blank line is required before the mark. This fixes that by ignoring any comments after the start of scope.
=> Fix `blankLinesAroundMark` not ignoring trailing comments at start of scope

Rules.md, Sources/OptionDescriptor.swift, Sources/Options.swift, Sources/RuleRegistry.generated.swift, Sources/Rules/RedundantThrows.swift, Tests/Rules/RedundantThrowsTests.swift
This PR adds a new `redundantThrows` rule.
If a function body doesn't include `try` or `throw`, then any `throws` keyword is redundant.
It's always safe to remove `throws` from test case methods, since those are never called directly:
```diff
// With --redundant-throws tests-only (default)
import Testing
- @Test func myFeature() throws {
+ @Test func myFeature() throws {
#expect(foo == 1)
}
import XCTest
class TestCase: XCTestCase {
-     func testMyFeature() throws {
+     func testMyFeature() {
XCTAssertEqual(foo, 1)
}
}
```
We can also apply this outside of tests, but this will cause additional warnings anywhere the now-non-throwing function is called with a redundant `try` keyword:
```diff
// With --redundant-throws always
- func myNonThrowingMethod() throws -> Int {
+ func …
```
=> Add `redundantThrows` rule

Rules.md, Sources/Rules/NoForceUnwrapInTests.swift, Tests/CodeOrganizationTests.swift, Tests/Rules/NoForceUnwrapInTestsTests.swift
This PR improves support for `XCTAssertEqual` /`XCTAssertNil` / `#expect(value == ...)` in `noForceUnwrapInTests`:
`XCTUnwrap` / `#require` is unnecessary in these cases, and omitting it results in more idiomatic code:
- `XCTAssertEqual(try XCTUnwrap(foo?.bar), baaz)` can just be `XCTAssertEqual(foo?.bar, baaz)`
- `XCTAssertNil(try XCTUnwrap(foo?.bar))` would cause a runtime test failure, and should just be `XCTAssertNil(foo?.bar)`
- Same for `#expect(foo?.bar == baaz)` and `#expect(foo?.bar == nil)`
=> Improve support for `XCTAssertEqual` and `XCTAssertNil` in `noForceUnwrapInTests`

Sources/Rules/TrailingCommas.swift, Sources/SwiftFormat.swift, Tests/Rules/TrailingCommasTests.swift
Swift 6.1 had bugs that unexpectedly disallowed trailing commas in a few places, like tuple values and generic argument lists (https://github.com/swiftlang/swift/pull/81612).
This PR updates the `trailingCommas` rule to add trailing commas in these places with using Swift 6.2.
I found a remaining edge case in Swift 6.2 where trailing commas are still not supported in tuple values _within generic argument lists_. Working on landing a fix for that in Swift 6.3: https://github.com/swiftlang/swift-syntax/pull/3153.
I'll release a new SwiftFormat version including this change after verifying that the Airbnb codebase compiles properly in Swift 6.2 after applying the updated `trailingCommas` functionality.
=> Update `trailingCommas` rule to support bug fixes in Swift 6.2

Sources/Rules/TrailingCommas.swift, Tests/Rules/TrailingCommasTests.swift
This PR updates the `trailingCommas` rule to handle a Swift 6.2 bug where trailing commas are unexpectedly not allowed in closure literal tuple return types.
This example does not compile in Swift 6.2:
```swift
let closure = { () -> (
foo: String,
bar: String,
) in
(foo: "foo", bar: "bar")
}
```
I confirmed this fix also fixes this issue, so this should be supported in Swift 6.3: https://github.com/swiftlang/swift/pull/84421
=> Handle Swift 6.2 bug where trailing commas are not allowed in closure literal tuple return types

Sources/Formatter.swift, Sources/Rules/TrailingClosures.swift, Tests/Rules/TrailingClosuresTests.swift
This PR fixes https://github.com/nicklockwood/SwiftFormat/issues/2223
=> Improve `trailingClosures` support for multiple trailing closures, fix bug where trailing closures could be applied to ineligible function calls

Sources/ParsingHelpers.swift, Tests/Rules/WrapAttributesTests.swift
Fixes https://github.com/nicklockwood/SwiftFormat/issues/2215.
=> Fix issue where `wrapAttributes` rule would unexpectedly wrap `async` effect

Sources/SwiftFormat.swift, Tests/CommandLineTests.swift
This PR fixes an issue where any `.swift-version` file was ignored if not also using a config file. Fixes https://github.com/nicklockwood/SwiftFormat/issues/2221.
=> Fix issue where `.swift-version` file was ignored if not also using config file

Sources/Rules/RedundantInit.swift, Tests/Rules/RedundantInitTests.swift
This PR updates the `redundantInit` rule to support function calls with single trailing closure arguments.
```diff
- Handler.init { print("foo") }
+ Handler { print("foo") }
```
=> Update `redundantInit` rule to support function calls with single trailing closure argument
